/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.cloudflare-provider-executor.jsonc --include-runtime=false cloudflare-provider-executor-worker-configuration.d.ts` (hash: 71240da5eee94962807701d083e6cd3f)
interface __BaseEnv_Env {
  OBJECTS: R2Bucket;
  STATE_DB: D1Database;
  DISPATCHER: DispatchNamespace;
  PUBLIC_ORIGIN: "https://unconfigured.invalid";
  CLOUDFLARE_ACCOUNT_ID: "unconfigured";
  TAKOSERVER_ZONES: "[]";
  TAKOSERVER_CLOUDFLARE_DISPATCH_NAMESPACE: "unconfigured";
  TAKOSERVER_MANAGED_WORKER_GATEWAY_NAME: "unconfigured";
  TAKOSERVER_MANAGED_BASE_DOMAIN: "unconfigured.invalid";
  TAKOSERVER_CLOUDFLARE_PROVIDER_INSTALLATION_ID: "unconfigured";
  TAKOSERVER_CLOUDFLARE_RELEASE_READBACK_QUALIFICATION: "{}";
  TAKOSERVER_MANAGED_OBJECT_RECEIPT_AUTHORITY_NAME: "unconfigured";
  CLOUDFLARE_API_TOKEN: string;
  TAKOSERVER_RUNTIME_INPUT_SEAL_KEYRING: string;
  SQLITE_DATABASES: DurableObjectNamespace /* TakoserverManagedWorkerSqlite from unconfigured */;
  MANAGED_WORKER_AUTHORITY: Service /* entrypoint TakoserverManagedWorkerAuthority from unconfigured */;
  MANAGED_OBJECT_RECEIPT_AUTHORITY: Service /* entrypoint TakoserverManagedObjectReceiptAuthority from unconfigured */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/entry-cloudflare-provider-executor");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "PUBLIC_ORIGIN"
        | "CLOUDFLARE_ACCOUNT_ID"
        | "TAKOSERVER_ZONES"
        | "TAKOSERVER_CLOUDFLARE_DISPATCH_NAMESPACE"
        | "TAKOSERVER_MANAGED_WORKER_GATEWAY_NAME"
        | "TAKOSERVER_MANAGED_BASE_DOMAIN"
        | "TAKOSERVER_CLOUDFLARE_PROVIDER_INSTALLATION_ID"
        | "TAKOSERVER_CLOUDFLARE_RELEASE_READBACK_QUALIFICATION"
        | "TAKOSERVER_MANAGED_OBJECT_RECEIPT_AUTHORITY_NAME"
        | "CLOUDFLARE_API_TOKEN"
        | "TAKOSERVER_RUNTIME_INPUT_SEAL_KEYRING"
      >
    > {}
}
