/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.exact-artifact-recovery.jsonc --include-runtime=false --env-interface=ExactArtifactRecoveryWorkerEnv exact-artifact-recovery-worker-configuration.d.ts` (hash: b97a88c7558fd7e31d642308fb357868)
interface __BaseEnv_ExactArtifactRecoveryWorkerEnv {
  OBJECTS: R2Bucket;
  STATE_DB: D1Database;
  WORKER_VERSION: WorkerVersionMetadata;
  TAKOSERVER_ENVIRONMENT: "integration";
  TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
  TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK: "unconfigured";
  TAKOSERVER_EXACT_ARTIFACT_RECOVERY_REQUEST_DIGEST: "sha256:0000000000000000000000000000000000000000000000000000000000000000";
  TAKOSERVER_EXACT_ARTIFACT_RECOVERY_R2_IDENTITY_DIGEST: "sha256:0000000000000000000000000000000000000000000000000000000000000000";
  TAKOSERVER_EXACT_ARTIFACT_RECOVERY_SOURCE_COMMIT: "0000000000000000000000000000000000000000";
  TAKOSERVER_EXACT_ARTIFACT_RECOVERY_SOURCE_VERSION: "unconfigured";
  PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/entry-exact-artifact-recovery-worker");
  }
  interface Env extends __BaseEnv_ExactArtifactRecoveryWorkerEnv {}
}
interface ExactArtifactRecoveryWorkerEnv extends __BaseEnv_ExactArtifactRecoveryWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "TAKOSERVER_ENVIRONMENT"
        | "TAKOSERVER_FORM_AUTHORITY_HOST_ID"
        | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK"
        | "TAKOSERVER_EXACT_ARTIFACT_RECOVERY_REQUEST_DIGEST"
        | "TAKOSERVER_EXACT_ARTIFACT_RECOVERY_R2_IDENTITY_DIGEST"
        | "TAKOSERVER_EXACT_ARTIFACT_RECOVERY_SOURCE_COMMIT"
        | "TAKOSERVER_EXACT_ARTIFACT_RECOVERY_SOURCE_VERSION"
      >
    > {}
}
