/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.existing-space-operator.jsonc --include-runtime=false --env-interface=ExistingSpaceOperatorWorkerEnv existing-space-operator-worker-configuration.d.ts` (hash: b57592b0a4f2e24373663f4193213507)
interface __BaseEnv_ExistingSpaceOperatorWorkerEnv {
	TAKOSERVER_ENVIRONMENT: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
	TAKOSERVER_EXISTING_SPACE_OPERATOR_ORIGIN: "https://unconfigured.invalid";
	TAKOSERVER_EXISTING_SPACE_OPERATOR_PUBLIC_JWK: "unconfigured";
	TAKOSERVER_MANAGED_SPACE_ADMISSION_POLICY: "unconfigured";
	FORM_AUTHORITY: Service /* entrypoint FormAuthorityEntrypoint from takoserver-form-authority */;
	PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-existing-space-operator-worker");
	}
	interface Env extends __BaseEnv_ExistingSpaceOperatorWorkerEnv {}
}
interface ExistingSpaceOperatorWorkerEnv extends __BaseEnv_ExistingSpaceOperatorWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_ENVIRONMENT" | "TAKOSERVER_FORM_AUTHORITY_HOST_ID" | "TAKOSERVER_EXISTING_SPACE_OPERATOR_ORIGIN" | "TAKOSERVER_EXISTING_SPACE_OPERATOR_PUBLIC_JWK" | "TAKOSERVER_MANAGED_SPACE_ADMISSION_POLICY">> {}
}
