/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.form-authority.jsonc --include-runtime=false --env-interface=FormAuthorityWorkerEnv form-authority-worker-configuration.d.ts` (hash: 781d1215255e935a94dfef835adf92b4)
interface __BaseEnv_FormAuthorityWorkerEnv {
	OBJECTS: R2Bucket;
	STATE_DB: D1Database;
	TAKOSERVER_ENVIRONMENT: "production";
	TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
	TAKOSERVER_PUBLIC_WORKER_ARTIFACT_DIGEST: "unconfigured";
	TAKOSERVER_PUBLIC_WORKER_VERSION_ID: "00000000-0000-0000-0000-000000000000";
	TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST: "unconfigured";
	PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-form-authority-worker");
	}
	interface Env extends __BaseEnv_FormAuthorityWorkerEnv {}
}
interface FormAuthorityWorkerEnv extends __BaseEnv_FormAuthorityWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_ENVIRONMENT" | "TAKOSERVER_FORM_AUTHORITY_HOST_ID" | "TAKOSERVER_PUBLIC_WORKER_ARTIFACT_DIGEST" | "TAKOSERVER_PUBLIC_WORKER_VERSION_ID" | "TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST">> {}
}
