/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.form-authority.jsonc --include-runtime=false --env-interface=FormAuthorityWorkerEnv form-authority-worker-configuration.d.ts` (hash: 8f074a27fffb6d775744f6455a04f542)
interface __BaseEnv_FormAuthorityWorkerEnv {
	OBJECTS: R2Bucket;
	STATE_DB: D1Database;
	TAKOSERVER_ENVIRONMENT: "production";
	TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
	TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST: "unconfigured";
	TAKOSERVER_TAKOFORM_CORE_VERIFIER_ARTIFACT_DIGEST: "sha256:0000000000000000000000000000000000000000000000000000000000000000";
	CORE_VERIFIER: DurableObjectNamespace<import("./src/entry-form-authority-worker").TakoformCoreVerifierContainer>;
	PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-form-authority-worker");
		durableNamespaces: "TakoformCoreVerifierContainer";
	}
	interface Env extends __BaseEnv_FormAuthorityWorkerEnv {}
}
interface FormAuthorityWorkerEnv extends __BaseEnv_FormAuthorityWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_ENVIRONMENT" | "TAKOSERVER_FORM_AUTHORITY_HOST_ID" | "TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST" | "TAKOSERVER_TAKOFORM_CORE_VERIFIER_ARTIFACT_DIGEST">> {}
}
