/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.form-authority-identity-probe.jsonc --include-runtime=false --env-interface=FormAuthorityIdentityProbeWorkerEnv form-authority-identity-probe-worker-configuration.d.ts` (hash: 8b039cb26ac3fab26895c3b478f74a66)
interface __BaseEnv_FormAuthorityIdentityProbeWorkerEnv {
  TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
  PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
  FORM_AUTHORITY: Service /* entrypoint FormAuthorityEntrypoint from takoserver-form-authority */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/entry-form-authority-identity-probe");
  }
  interface Env extends __BaseEnv_FormAuthorityIdentityProbeWorkerEnv {}
}
interface FormAuthorityIdentityProbeWorkerEnv
  extends __BaseEnv_FormAuthorityIdentityProbeWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_FORM_AUTHORITY_HOST_ID">> {}
}
