/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.integration-form-authority.jsonc --include-runtime=false --env-interface=IntegrationFormAuthorityWorkerEnv integration-form-authority-worker-configuration.d.ts` (hash: 4ae204c34520181b186b6588ba7e2273)
interface __BaseEnv_IntegrationFormAuthorityWorkerEnv {
	OBJECTS: R2Bucket;
	STATE_DB: D1Database;
	TAKOSERVER_ENVIRONMENT: "integration";
	TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
	TAKOSERVER_PUBLIC_WORKER_ARTIFACT_DIGEST: "unconfigured";
	TAKOSERVER_PUBLIC_WORKER_VERSION_ID: "00000000-0000-0000-0000-000000000000";
	TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_TENANT_ID: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_SPACE: "unconfigured";
	PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-integration-form-authority-worker");
	}
	interface Env extends __BaseEnv_IntegrationFormAuthorityWorkerEnv {}
}
interface IntegrationFormAuthorityWorkerEnv extends __BaseEnv_IntegrationFormAuthorityWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_ENVIRONMENT" | "TAKOSERVER_FORM_AUTHORITY_HOST_ID" | "TAKOSERVER_PUBLIC_WORKER_ARTIFACT_DIGEST" | "TAKOSERVER_PUBLIC_WORKER_VERSION_ID" | "TAKOSERVER_FORM_AUTHORITY_CAPABILITY_MANIFEST" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_TENANT_ID" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_SPACE">> {}
}
