/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.integration-form-authority-operator.jsonc --include-runtime=false --env-interface=IntegrationFormAuthorityOperatorWorkerEnv integration-form-authority-operator-worker-configuration.d.ts` (hash: 11cd0a00904bbc3bc49b014a8c2193c8)
interface __BaseEnv_IntegrationFormAuthorityOperatorWorkerEnv {
	TAKOSERVER_ENVIRONMENT: "integration";
	TAKOSERVER_FORM_AUTHORITY_HOST_ID: "unconfigured.invalid";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_ORIGIN: "https://unconfigured.invalid";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_TENANT_ID: "unconfigured";
	TAKOSERVER_FORM_AUTHORITY_OPERATOR_SPACE: "unconfigured";
	FORM_AUTHORITY: Service /* entrypoint IntegrationFormAuthorityEntrypoint from takoserver-integration-form-authority */;
	PUBLIC_HOST_IDENTITY: Service /* entrypoint PublicHostIdentityEntrypoint from takoserver-api */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-integration-form-authority-operator-worker");
	}
	interface Env extends __BaseEnv_IntegrationFormAuthorityOperatorWorkerEnv {}
}
interface IntegrationFormAuthorityOperatorWorkerEnv extends __BaseEnv_IntegrationFormAuthorityOperatorWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_ENVIRONMENT" | "TAKOSERVER_FORM_AUTHORITY_HOST_ID" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_ORIGIN" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_PUBLIC_JWK" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_TENANT_ID" | "TAKOSERVER_FORM_AUTHORITY_OPERATOR_SPACE">> {}
}
