/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.managed-object-receipt-authority.jsonc --include-runtime=false managed-object-receipt-authority-worker-configuration.d.ts` (hash: c788723b6ce603404b191c94fdb6d986)
interface __BaseEnv_Env {
  MANAGED_PROVIDER_ID: "unconfigured";
  TAKOSERVER_MANAGED_OBJECT_ACCOUNT_ID: "unconfigured";
  TAKOSERVER_MANAGED_OBJECT_ACCESS_KEY_ID: string;
  TAKOSERVER_MANAGED_OBJECT_SECRET_ACCESS_KEY: string;
  TAKOSERVER_MANAGED_OBJECT_PROOF_SECRET: string;
  OBJECT_RECEIPTS: DurableObjectNamespace<
    import("./src/entry-cloudflare-managed-object-receipt-authority").TakoserverManagedObjectReceipt
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/entry-cloudflare-managed-object-receipt-authority");
    durableNamespaces: "TakoserverManagedObjectReceipt";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "MANAGED_PROVIDER_ID"
        | "TAKOSERVER_MANAGED_OBJECT_ACCOUNT_ID"
        | "TAKOSERVER_MANAGED_OBJECT_ACCESS_KEY_ID"
        | "TAKOSERVER_MANAGED_OBJECT_SECRET_ACCESS_KEY"
        | "TAKOSERVER_MANAGED_OBJECT_PROOF_SECRET"
      >
    > {}
}
