/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.managed-worker-gateway.jsonc --include-runtime=false managed-worker-gateway-worker-configuration.d.ts` (hash: 9b43c958668f9a4a09dcac1f0075558a)
interface __BaseEnv_Env {
  STATE_DB: D1Database;
  DISPATCHER: DispatchNamespace;
  TAKOSERVER_MANAGED_WORKER_GATEWAY_ID: "unconfigured";
  TAKOSERVER_ENVIRONMENT: "unconfigured";
  MANAGED_PROVIDER_ID: "unconfigured";
  SQLITE_DATABASES: DurableObjectNamespace<
    import("./src/entry-cloudflare-managed-worker-gateway").TakoserverManagedWorkerSqlite
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/entry-cloudflare-managed-worker-gateway");
    durableNamespaces: "TakoserverManagedWorkerSqlite";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        "TAKOSERVER_MANAGED_WORKER_GATEWAY_ID" | "TAKOSERVER_ENVIRONMENT" | "MANAGED_PROVIDER_ID"
      >
    > {}
}
