/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.sponsorship-authority.jsonc --include-runtime=false --env-interface=SponsorshipAuthorityWorkerEnv sponsorship-authority-worker-configuration.d.ts` (hash: c46851a005697110cf01c224d92ba09b)
interface __BaseEnv_SponsorshipAuthorityWorkerEnv {
	STATE_DB: D1Database;
	WORKER_VERSION: WorkerVersionMetadata;
	TAKOSERVER_SPONSORSHIP_ORGANIZATION_ID: "unconfigured";
	TAKOSERVER_SPONSORSHIP_TOKEN_ISSUER: "https://unconfigured.invalid";
	TAKOSERVER_SPONSORSHIP_CREDENTIAL_KEY_ID: "unconfigured";
	TAKOSERVER_SPONSORSHIP_CREDENTIAL_PUBLIC_JWK: "{\"kty\":\"OKP\",\"crv\":\"Ed25519\",\"x\":\"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\"}";
	TAKOSERVER_SPONSORSHIP_RECEIPT_KEY_ID: "unconfigured";
	TAKOSERVER_SPONSORSHIP_AUTHORITY_WORKER_NAME: "takoserver-sponsorship-authority";
	TAKOSERVER_SPONSORSHIP_AUTHORITY_SOURCE_COMMIT: "0000000000000000000000000000000000000000";
	TAKOSERVER_SPONSORSHIP_AUTHORITY_ARTIFACT_SHA256: "sha256:0000000000000000000000000000000000000000000000000000000000000000";
	TAKOSERVER_SPONSORSHIP_CREDENTIAL_SIGNING_KEY: string;
	TAKOSERVER_SPONSORSHIP_RECEIPT_SIGNING_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-sponsorship-authority-worker");
	}
	interface Env extends __BaseEnv_SponsorshipAuthorityWorkerEnv {}
}
interface SponsorshipAuthorityWorkerEnv extends __BaseEnv_SponsorshipAuthorityWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TAKOSERVER_SPONSORSHIP_ORGANIZATION_ID" | "TAKOSERVER_SPONSORSHIP_TOKEN_ISSUER" | "TAKOSERVER_SPONSORSHIP_CREDENTIAL_KEY_ID" | "TAKOSERVER_SPONSORSHIP_CREDENTIAL_PUBLIC_JWK" | "TAKOSERVER_SPONSORSHIP_RECEIPT_KEY_ID" | "TAKOSERVER_SPONSORSHIP_AUTHORITY_WORKER_NAME" | "TAKOSERVER_SPONSORSHIP_AUTHORITY_SOURCE_COMMIT" | "TAKOSERVER_SPONSORSHIP_AUTHORITY_ARTIFACT_SHA256" | "TAKOSERVER_SPONSORSHIP_CREDENTIAL_SIGNING_KEY" | "TAKOSERVER_SPONSORSHIP_RECEIPT_SIGNING_KEY">> {}
}
