/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 46b84e67305d76145f3f0482b01478bd)
interface __BaseEnv_Env {
	OBJECTS: R2Bucket;
	STATE_DB: D1Database;
	AI: Ai;
	WORKER_VERSION: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-cloudflare-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
