/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: a5a48f3d22fb81fa39a95f8efe12e7da)
interface __BaseEnv_Env {
	OBJECTS: R2Bucket;
	STATE_DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
