import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DeployError } from "../scripts/deploy/errors.ts";
import type { CommandResult } from "../scripts/deploy/process.ts";
import type { DeployTarget } from "../scripts/deploy/target.ts";
import {
  authoritySensitiveWorkerPaths,
  probeProduct,
  runWorker,
  type WorkerMigrationReader,
  type WorkerProcess,
  type WorkerState,
} from "../scripts/deploy/worker.ts";
import { expectedExactBindingClosure } from "../scripts/deploy/worker-state.ts";

const COMMIT = "a".repeat(40);
const LIVE_COMMIT = "b".repeat(40);
const BUNDLE = "export default {fetch(){return new Response('ok')}};\n";

const target = {
  kind: "takoserver.deploy-target@v2",
  environment: "integration",
  accountId: "a".repeat(32),
  workerName: "takoserver-api-integration",
  d1: {
    databaseName: "takoserver-runtime-integration",
    databaseId: "00000000-0000-4000-8000-000000000000",
  },
  r2: { bucketName: "takoserver-objects-integration" },
  publicOrigin: "https://api.integration.example.test",
  signing: { currentKeyId: "key-current" },
} satisfies DeployTarget;

function fixture(
  input: {
    readonly diff?: string;
    readonly dirty?: string;
    readonly applied?: readonly string[];
  } = {},
): {
  readonly run: WorkerProcess;
  readonly calls: string[][];
  readonly state: WorkerState;
  readonly migrations: WorkerMigrationReader;
} {
  const calls: string[][] = [];
  let historyReads = 0;
  let uploadMessage: string | null = null;
  const run: WorkerProcess = async (command): Promise<CommandResult> => {
    calls.push([...command]);
    const key = command.join(" ");
    if (key === "git rev-parse HEAD") return ok(`${COMMIT}\n`);
    if (key === "git branch --show-current") return ok("feature/worker\n");
    if (key === "git status --porcelain=v1 -z --untracked-files=all") {
      return ok(input.dirty ?? "");
    }
    if (key === `git diff --name-only ${LIVE_COMMIT}..${COMMIT} --`) {
      return ok(input.diff ?? "src/catalog.ts\n");
    }
    if (key === "bun run check") return ok("green\n");
    if (command.includes("--dry-run")) {
      const out = command[command.indexOf("--outdir") + 1];
      if (!out) throw new Error("dry-run output missing");
      mkdirSync(out, { recursive: true });
      writeFileSync(join(out, "index.js"), BUNDLE);
      writeFileSync(join(out, "index.js.map"), "{}\n");
      writeFileSync(join(out, "README.md"), "generated by Wrangler\n");
      return ok("Total Upload: 1 KiB\n");
    }
    if (command.includes("deploy") && command.includes("--no-bundle")) {
      uploadMessage = command[command.indexOf("--message") + 1] ?? null;
      return ok("Uploaded\n");
    }
    throw new Error(`unexpected command: ${key}`);
  };
  const state: WorkerState = {
    async workerDomains() {
      return [{ hostname: "api.integration.example.test", service: target.workerName }];
    },
    async workerDeployments() {
      historyReads += 1;
      return historyReads === 1
        ? [deployment("deployment-before", "version-before", "2026-08-28T01:00:00Z")]
        : [
            deployment("deployment-after", "version-after", "2026-08-28T02:00:00Z"),
            deployment("deployment-before", "version-before", "2026-08-28T01:00:00Z"),
          ];
    },
    async workerVersion(_worker, versionId) {
      return version(
        versionId,
        versionId === "version-before"
          ? `takoserver-worker:${LIVE_COMMIT}:${"c".repeat(64)}`
          : (uploadMessage ?? "missing"),
      );
    },
    async workerSecrets() {
      return [{ name: "TAKOSERVER_SIGNING_KEY", type: "secret_text" }];
    },
  };
  return {
    run,
    calls,
    state,
    migrations: {
      async read() {
        return {
          local: ["0001_first.sql", "0002_second.sql"],
          applied: input.applied ?? ["0001_first.sql", "0002_second.sql"],
        };
      },
    },
  };
}

describe("split Takoserver Worker surfaces", () => {
  test("published product and OpenAPI stay bound to the exact target origin", async () => {
    const fetcher = publishedProductFetcher();
    await expect(probeProduct(target.publicOrigin, fetcher)).resolves.toMatchObject({
      url: `${target.publicOrigin}/.well-known/takoserver`,
      status: 200,
      openapi: { url: `${target.publicOrigin}/openapi.json`, status: 200 },
    });
    await expect(
      probeProduct(
        target.publicOrigin,
        publishedProductFetcher({ openApiOrigin: "https://api.example.test" }),
      ),
    ).rejects.toThrow("OpenAPI server");
    await expect(
      probeProduct(
        target.publicOrigin,
        publishedProductFetcher({ discoveryOrigin: "https://api.example.test" }),
      ),
    ).rejects.toThrow("wrong product or origin");
  });

  test("classifies authentication, authorization, and deploy-mechanism paths as authority", () => {
    expect(
      authoritySensitiveWorkerPaths([
        "src/auth.ts",
        "src/app.ts",
        "src/control.ts",
        "src/takoform/admission.ts",
        "scripts/deploy/worker.ts",
        "wrangler.jsonc",
        "src/catalog.ts",
      ]),
    ).toEqual([
      "scripts/deploy/worker.ts",
      "src/app.ts",
      "src/auth.ts",
      "src/control.ts",
      "src/takoform/admission.ts",
      "wrangler.jsonc",
    ]);
  });

  test("routine refuses pending migrations before its gate or upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-pending-"));
    try {
      const current = fixture({ applied: ["0001_first.sql"] });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("pending D1 migrations");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
      expect(current.calls.some((call) => call.includes("--no-bundle"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("routine routes an authority-sensitive diff to the separate cutover", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-sensitive-"));
    try {
      const current = fixture({ diff: "src/auth.ts\nsrc/catalog.ts\n" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("takoserver-worker-authority-cutover");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("routine also routes an uncommitted authority-sensitive path", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-dirty-sensitive-"));
    try {
      const current = fixture({ diff: "", dirty: " M src/token.ts\0" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("takoserver-worker-authority-cutover");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("authority cutover needs review then seals one bundle/config for one upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-authority-"));
    try {
      const current = fixture({ diff: "src/auth.ts\n" });
      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      );
      expect(result).toMatchObject({
        kind: "takoserver.worker-apply@v2",
        surface: "takoserver-worker-authority-cutover",
        commit: COMMIT,
        previousVersionId: "version-before",
        versionId: "version-after",
        reviewer: "reviewer@example.test",
      });
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(1);
      expect(current.calls.filter((call) => call.includes("--dry-run"))).toHaveLength(1);
      const uploads = current.calls.filter((call) => call.includes("--no-bundle"));
      expect(uploads).toHaveLength(1);
      expect(uploads[0]).toContain("--strict");
      expect(uploads[0]?.find((value) => value.startsWith("takoserver-worker:"))).toMatch(
        /^takoserver-worker:[0-9a-f]{40}:[0-9a-f]{64}$/u,
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

function publishedProductFetcher(
  options: { readonly discoveryOrigin?: string; readonly openApiOrigin?: string } = {},
) {
  const discoveryOrigin = options.discoveryOrigin ?? target.publicOrigin;
  const openApiOrigin = options.openApiOrigin ?? target.publicOrigin;
  return async (input: string): Promise<Response> => {
    const pathname = new URL(input).pathname;
    if (pathname === "/.well-known/takoserver") {
      return Response.json({
        product: "takoserver",
        apiVersion: "v1",
        endpoints: {
          api: discoveryOrigin,
          openapi: `${discoveryOrigin}/openapi.json`,
        },
      });
    }
    if (pathname === "/openapi.json") {
      return Response.json({ servers: [{ url: openApiOrigin }] });
    }
    return Response.json({ error: "not_found" }, { status: 404 });
  };
}

function deployment(id: string, versionId: string, created: string) {
  return {
    id,
    created_on: created,
    versions: [{ version_id: versionId, percentage: 100 }],
  };
}

function version(id: string, message: string) {
  const expected = expectedExactBindingClosure(target, { hostedTopology: "desired" });
  return {
    id,
    annotations: { "workers/message": message },
    resources: {
      bindings: Object.entries(expected).flatMap(([name, requirement]) =>
        requirement === null ? [] : [{ name, type: requirement.type, ...requirement.fields }],
      ),
    },
  };
}

function ok(stdout: string): CommandResult {
  return { exitCode: 0, stdout, stderr: "" };
}
