import { describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DeployError } from "../scripts/deploy/errors.ts";
import type { CommandResult } from "../scripts/deploy/process.ts";
import type { DeployTarget } from "../scripts/deploy/target.ts";
import {
  authoritySensitiveWorkerPaths,
  probeProduct,
  runWorker,
  type WorkerMigrationReader,
  type WorkerProcess,
  type WorkerState,
} from "../scripts/deploy/worker.ts";
import {
  authorityImplementationClosure,
  declaredAuthorityModulePaths,
  publicFormIdentityAuthorityPaths,
} from "../scripts/deploy/worker-authority-paths.ts";
import { expectedExactBindingClosure } from "../scripts/deploy/worker-state.ts";
import { INTEGRATION_E2E_ORGANIZATION_ID } from "../src/integration-e2e-credential-authority.ts";

const COMMIT = "a".repeat(40);
const LIVE_COMMIT = "b".repeat(40);
const BUNDLE = "export default {fetch(){return new Response('ok')}};\n";
const VERSION_BEFORE = "00000000-0000-4000-8000-000000000001";
const VERSION_AFTER = "00000000-0000-4000-8000-000000000002";
const VERSION_UNRELATED = "00000000-0000-4000-8000-000000000003";
const VERSION_UNRELATED_PREVIOUS = "00000000-0000-4000-8000-000000000004";
const OTHER_COMMIT = "d".repeat(40);

const target = {
  kind: "takoserver.deploy-target@v2",
  environment: "integration",
  accountId: "a".repeat(32),
  workerName: "takoserver-api-integration",
  d1: {
    databaseName: "takoserver-runtime-integration",
    databaseId: "00000000-0000-4000-8000-000000000000",
  },
  r2: { bucketName: "takoserver-objects-integration" },
  publicOrigin: "https://api.integration.example.test",
  signing: { currentKeyId: "key-current" },
} satisfies DeployTarget;

function fixture(
  input: {
    readonly diff?: string;
    readonly dirty?: string;
    readonly applied?: readonly string[];
    readonly beforeMessage?: string | null;
    readonly beforeMessageAfterBuild?: string | null;
    readonly afterMessage?: string | null;
    readonly unrelatedMessage?: string | null;
    readonly current?: "before" | "after" | "unrelated";
    readonly advanceDuringBuild?: boolean;
    readonly secretsAfterBuild?: readonly unknown[];
    readonly legacyBeforeWithoutVersionMetadata?: boolean;
    readonly beforeVersionMetadataAfterBuild?: boolean;
    readonly afterWithoutVersionMetadata?: boolean;
    readonly replaceDeploymentDuringFinalInspection?: boolean;
  } = {},
): {
  readonly run: WorkerProcess;
  readonly calls: string[][];
  readonly state: WorkerState;
  readonly migrations: WorkerMigrationReader;
} {
  const calls: string[][] = [];
  let current = input.current ?? "before";
  let built = false;
  let replacementObserved = false;
  let uploadMessage: string | null = null;
  const run: WorkerProcess = async (command): Promise<CommandResult> => {
    calls.push([...command]);
    const key = command.join(" ");
    if (key === "git rev-parse HEAD") return ok(`${COMMIT}\n`);
    if (key === "git branch --show-current") return ok("feature/worker\n");
    if (key === "git status --porcelain=v1 -z --untracked-files=all") {
      return ok(input.dirty ?? "");
    }
    if (key === `git diff --name-only ${LIVE_COMMIT}..${COMMIT} --`) {
      return ok(input.diff ?? "src/catalog.ts\n");
    }
    if (key === "bun run check") return ok("green\n");
    if (command.includes("--dry-run")) {
      const out = command[command.indexOf("--outdir") + 1];
      if (!out) throw new Error("dry-run output missing");
      mkdirSync(out, { recursive: true });
      writeFileSync(join(out, "index.js"), BUNDLE);
      writeFileSync(join(out, "index.js.map"), "{}\n");
      writeFileSync(join(out, "README.md"), "generated by Wrangler\n");
      built = true;
      if (input.advanceDuringBuild === true) current = "after";
      return ok("Total Upload: 1 KiB\n");
    }
    if (command.includes("deploy") && command.includes("--no-bundle")) {
      uploadMessage = command[command.indexOf("--message") + 1] ?? null;
      current = "after";
      return ok("Uploaded\n");
    }
    throw new Error(`unexpected command: ${key}`);
  };
  const state: WorkerState = {
    async workerDomains() {
      return [{ hostname: "api.integration.example.test", service: target.workerName }];
    },
    async workerDeployments() {
      if (current === "before") {
        if (replacementObserved) {
          return [deployment("deployment-before-replaced", VERSION_BEFORE, "2026-08-28T04:00:00Z")];
        }
        return [deployment("deployment-before", VERSION_BEFORE, "2026-08-28T01:00:00Z")];
      }
      if (current === "unrelated") {
        return [
          deployment("deployment-unrelated", VERSION_UNRELATED, "2026-08-28T03:00:00Z"),
          deployment(
            "deployment-unrelated-previous",
            VERSION_UNRELATED_PREVIOUS,
            "2026-08-28T02:00:00Z",
          ),
        ];
      }
      return [
        deployment("deployment-after", VERSION_AFTER, "2026-08-28T02:00:00Z"),
        deployment("deployment-before", VERSION_BEFORE, "2026-08-28T01:00:00Z"),
      ];
    },
    async workerVersion(_worker, versionId) {
      const result = version(
        versionId,
        versionId === VERSION_BEFORE
          ? built && input.beforeMessageAfterBuild !== undefined
            ? input.beforeMessageAfterBuild
            : input.beforeMessage === undefined
              ? `takoserver-worker:${LIVE_COMMIT}:${"c".repeat(64)}`
              : input.beforeMessage
          : versionId === VERSION_AFTER
            ? input.afterMessage === undefined
              ? (uploadMessage ?? "missing")
              : input.afterMessage
            : input.unrelatedMessage === undefined
              ? `takoserver-worker:${OTHER_COMMIT}:${"e".repeat(64)}`
              : input.unrelatedMessage,
        versionId === VERSION_BEFORE &&
          input.legacyBeforeWithoutVersionMetadata === true &&
          !(built && input.beforeVersionMetadataAfterBuild === true)
          ? "legacy-pre-version-metadata"
          : versionId === VERSION_AFTER && input.afterWithoutVersionMetadata === true
            ? "legacy-pre-version-metadata"
            : "current",
      );
      if (
        built &&
        versionId === VERSION_BEFORE &&
        input.replaceDeploymentDuringFinalInspection === true
      ) {
        replacementObserved = true;
      }
      return result;
    },
    async workerSecrets() {
      if (built && input.secretsAfterBuild !== undefined) return input.secretsAfterBuild;
      return [{ name: "TAKOSERVER_SIGNING_KEY", type: "secret_text" }];
    },
  };
  return {
    run,
    calls,
    state,
    migrations: {
      async read() {
        return {
          local: ["0001_first.sql", "0002_second.sql"],
          applied: input.applied ?? ["0001_first.sql", "0002_second.sql"],
        };
      },
    },
  };
}

describe("split Takoserver Worker surfaces", () => {
  test("published product and OpenAPI stay bound to the exact target origin", async () => {
    const fetcher = publishedProductFetcher();
    await expect(probeProduct(target.publicOrigin, fetcher)).resolves.toMatchObject({
      url: `${target.publicOrigin}/.well-known/takoserver`,
      status: 200,
      openapi: { url: `${target.publicOrigin}/openapi.json`, status: 200 },
    });
    await expect(
      probeProduct(
        target.publicOrigin,
        publishedProductFetcher({ openApiOrigin: "https://api.example.test" }),
      ),
    ).rejects.toThrow("OpenAPI server");
    await expect(
      probeProduct(
        target.publicOrigin,
        publishedProductFetcher({ discoveryOrigin: "https://api.example.test" }),
      ),
    ).rejects.toThrow("wrong product or origin");
  });

  test("classifies authentication, authorization, and deploy-mechanism paths as authority", () => {
    expect(
      authoritySensitiveWorkerPaths([
        "src/auth.ts",
        "src/app.ts",
        "src/control.ts",
        "src/entry-cloudflare-worker.ts",
        "src/public-host-identity.ts",
        "src/takoform/admission.ts",
        "src/takoform/host-authority.ts",
        "scripts/deploy/worker.ts",
        "wrangler.jsonc",
        "src/catalog.ts",
      ]),
    ).toEqual([
      "scripts/deploy/worker.ts",
      "src/app.ts",
      "src/auth.ts",
      "src/control.ts",
      "src/entry-cloudflare-worker.ts",
      "src/public-host-identity.ts",
      "src/takoform/admission.ts",
      "src/takoform/host-authority.ts",
      "wrangler.jsonc",
    ]);
  });

  test("classifies money, customer secrets, and the durable store as authority", () => {
    // Every one of these published as *routine* before the implementation
    // closure existed: the prepaid ledger, its Stripe settlement, the sealed
    // runtime-input handoff, the AES-256-GCM key ring that seals it, and the
    // durable Takoform resource store every later decision is read back from.
    const authorities = [
      "src/ledger.ts",
      "src/runtime-input-preparations.ts",
      "src/runtime-input-seal-keyring.ts",
      "src/stripe-settlement.ts",
      "src/takoform/store.ts",
    ];
    expect(authoritySensitiveWorkerPaths(authorities)).toEqual(authorities);
  });

  test("derives the money, secret, and durable-store closure from the import graph", () => {
    // A new runtime dependency of any of the five roots classifies without an
    // edit here. Every module below beyond the roots themselves was already
    // inside the public Form P/I closure, so making this walk authoritative
    // widened the reviewed lane by exactly the five roots and nothing else.
    expect(authorityImplementationClosure()).toEqual([
      "src/json.ts",
      "src/ledger.ts",
      "src/ports.ts",
      "src/provider-runtime-input-port.ts",
      "src/runtime-input-preparations.ts",
      "src/runtime-input-seal-keyring.ts",
      "src/stripe-settlement.ts",
      "src/takoform/limits.ts",
      "src/takoform/store.ts",
      "src/takoform/types.ts",
    ]);
    const previouslyClassified = new Set(publicFormIdentityAuthorityPaths());
    expect(
      authorityImplementationClosure().filter((path) => !previouslyClassified.has(path)),
    ).toEqual([
      "src/ledger.ts",
      "src/runtime-input-preparations.ts",
      "src/runtime-input-seal-keyring.ts",
      "src/stripe-settlement.ts",
      "src/takoform/store.ts",
    ]);
  });

  test("every classified authority path still exists in the tree", () => {
    // The classifier is exact paths and a resolved import graph rather than a
    // pattern, so a renamed authority refuses instead of quietly falling out of
    // a regex and publishing as routine.
    for (const path of [
      ...declaredAuthorityModulePaths(),
      ...authorityImplementationClosure(),
      ...publicFormIdentityAuthorityPaths(),
    ]) {
      expect(existsSync(join(import.meta.dir, "..", path))).toBe(true);
    }
  });

  test("keeps the routine lane open: rendering, catalog, and metering stay routine", () => {
    // The walk is not seeded from a composition root. `entry-worker.ts` reaches
    // 140 of the 182 modules under `src` and `app.ts` reaches 73, so seeding
    // there would classify almost the product and leave no routine lane at all.
    expect(
      authoritySensitiveWorkerPaths([
        "src/catalog.ts",
        "src/openapi.ts",
        "src/landing.ts",
        "src/metering.ts",
        "README.md",
      ]),
    ).toEqual([]);
    for (const reachedOnlyThroughAComposition of [
      "src/openapi.ts",
      "src/landing.ts",
      "src/catalog.ts",
    ]) {
      expect(authorityImplementationClosure()).not.toContain(reachedOnlyThroughAComposition);
    }
  });

  test("classifies every executable public Form P/I owner as authority", () => {
    const expected = [
      "src/entry-public-form-runtime-payload.ts",
      "src/error-envelope.ts",
      "src/form-ref.ts",
      "src/generated/takoform-stable-v1-catalog.ts",
      "src/json.ts",
      "src/ports.ts",
      "src/provider-driver.ts",
      "src/provider-placement.ts",
      "src/provider-port.ts",
      "src/provider-runtime-bindings.ts",
      "src/provider-runtime-input-port.ts",
      "src/provider-worker-endpoint-origin.ts",
      "src/providers/cloudflare-managed-worker-gateway.ts",
      "src/providers/cloudflare-managed-worker-wrapper.ts",
      "src/providers/cloudflare-runtime-bindings.ts",
      "src/providers/cloudflare-wfp-backend.ts",
      "src/providers/cloudflare-wfp-client.ts",
      "src/providers/cloudflare.ts",
      "src/providers/managed-worker-state.ts",
      "src/public-form-implementation-build.ts",
      "src/public-form-runtime.ts",
      "src/public-worker-implementation.ts",
      "src/strict-json.ts",
      "src/takoform/bindings.ts",
      "src/takoform/current-candidates.ts",
      "src/takoform/edge-family.ts",
      "src/takoform/edge-semantics.ts",
      "src/takoform/engine.ts",
      "src/takoform/forms.ts",
      "src/takoform/implementation-catalog.ts",
      "src/takoform/limits.ts",
      "src/takoform/receipt-projection.ts",
      "src/takoform/relations.ts",
      "src/takoform/schema.ts",
      "src/takoform/sqlite-migrations.ts",
      "src/takoform/standard-services.ts",
      "src/takoform/types.ts",
      "src/takoform/wire.ts",
      "src/takoform/worker-aggregate.ts",
      "src/takoform/worker-runtime-contract.ts",
      "src/worker-endpoint-origin-reservations.ts",
    ];
    expect(publicFormIdentityAuthorityPaths()).toEqual(expected);
    expect(authoritySensitiveWorkerPaths([...expected, "src/catalog.ts"])).toEqual(expected);
  });

  test("routine cannot publish public Form-authority fences without the reviewed cutover", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-public-authority-"));
    try {
      const current = fixture({
        diff: [
          "src/entry-cloudflare-worker.ts",
          "src/public-host-identity.ts",
          "src/takoform/host-authority.ts",
        ].join("\n"),
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("takoserver-worker-authority-cutover");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("routine refuses pending migrations before its gate or upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-pending-"));
    try {
      const current = fixture({ applied: ["0001_first.sql"] });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("pending D1 migrations");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
      expect(current.calls.some((call) => call.includes("--no-bundle"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("routine routes an authority-sensitive diff to the separate cutover", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-sensitive-"));
    try {
      const current = fixture({ diff: "src/auth.ts\nsrc/catalog.ts\n" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("takoserver-worker-authority-cutover");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("routine also routes an uncommitted authority-sensitive path", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-dirty-sensitive-"));
    try {
      const current = fixture({ diff: "", dirty: " M src/token.ts\0" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("takoserver-worker-authority-cutover");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("authority cutover needs review then seals one bundle/config for one upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-authority-"));
    try {
      const current = fixture({ diff: "src/auth.ts\n" });
      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      );
      expect(result).toMatchObject({
        kind: "takoserver.worker-apply@v2",
        surface: "takoserver-worker-authority-cutover",
        commit: COMMIT,
        previousVersionId: VERSION_BEFORE,
        versionId: VERSION_AFTER,
        reviewer: "reviewer@example.test",
      });
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(1);
      expect(current.calls.filter((call) => call.includes("--dry-run"))).toHaveLength(1);
      const uploads = current.calls.filter((call) => call.includes("--no-bundle"));
      expect(uploads).toHaveLength(1);
      expect(uploads[0]).toContain("--strict");
      expect(uploads[0]?.find((value) => value.startsWith("takoserver-worker:"))).toMatch(
        /^takoserver-worker:[0-9a-f]{40}:[0-9a-f]{64}$/u,
      );
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("only the integration authority cutover adds one complete provenance-bound JIT profile", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-jit-authority-"));
    const authorityTarget = {
      ...target,
      integrationE2eCredentialAuthority: {
        organizationId: INTEGRATION_E2E_ORGANIZATION_ID,
        publicJwk: { kty: "OKP", crv: "Ed25519", x: "E".repeat(43) },
      },
    } satisfies DeployTarget;
    try {
      const process = fixture({ diff: "src/auth.ts\n" });
      const activeSigningDatabase = signingDatabase(`${"F".repeat(42)}A`);
      const state: WorkerState = {
        async workerDomains() {
          return [{ hostname: "api.integration.example.test", service: target.workerName }];
        },
        async workerDeployments() {
          const uploaded = process.calls.some((call) => call.includes("--no-bundle"));
          return uploaded
            ? [
                deployment("deployment-after", VERSION_AFTER, "2026-08-28T02:00:00Z"),
                deployment("deployment-before", VERSION_BEFORE, "2026-08-28T01:00:00Z"),
              ]
            : [deployment("deployment-before", VERSION_BEFORE, "2026-08-28T01:00:00Z")];
        },
        async workerVersion(_worker, versionId) {
          if (versionId === VERSION_BEFORE) {
            return versionForTarget(
              versionId,
              `takoserver-worker:${LIVE_COMMIT}:${"c".repeat(64)}`,
              target,
            );
          }
          const upload = process.calls.find((call) => call.includes("--no-bundle"));
          const message = upload?.[upload.indexOf("--message") + 1];
          if (!message) throw new Error("missing upload annotation");
          return versionForTarget(versionId, message, authorityTarget);
        },
        async workerSecrets() {
          return [{ name: "TAKOSERVER_SIGNING_KEY", type: "secret_text" }];
        },
      };

      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        authorityTarget,
        {
          ...process,
          state,
          outputDirectory: root,
          signingDatabase: activeSigningDatabase,
        },
      );
      expect(status).toMatchObject({
        ready: false,
        integrationE2eCredentialAuthorityConfigured: false,
        versionId: VERSION_BEFORE,
      });

      const routine = await runWorker(
        {
          surface: "takoserver-worker",
          action: "status",
          environment: "integration",
          commit: COMMIT,
        },
        authorityTarget,
        {
          ...process,
          state,
          outputDirectory: root,
          signingDatabase: activeSigningDatabase,
        },
      ).catch((error) => error);
      expect(routine).toBeInstanceOf(DeployError);

      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        authorityTarget,
        {
          ...process,
          state,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
          signingDatabase: activeSigningDatabase,
        },
      );
      expect(result).toMatchObject({
        kind: "takoserver.worker-apply@v2",
        surface: "takoserver-worker-authority-cutover",
        commit: COMMIT,
        previousVersionId: VERSION_BEFORE,
        versionId: VERSION_AFTER,
      });
      const config = JSON.parse(readFileSync(join(root, "release/wrangler.jsonc"), "utf8")) as {
        vars: Record<string, string>;
      };
      expect(config.vars).toMatchObject({
        TAKOSERVER_ENVIRONMENT: "integration",
        TAKOSERVER_INTEGRATION_E2E_API_KEY_PUBLIC_JWK: JSON.stringify(
          authorityTarget.integrationE2eCredentialAuthority.publicJwk,
        ),
        TAKOSERVER_INTEGRATION_E2E_ORGANIZATION_ID: INTEGRATION_E2E_ORGANIZATION_ID,
        TAKOSERVER_SOURCE_COMMIT: COMMIT,
        TAKOSERVER_WORKER_ARTIFACT_DIGEST: result.bundleDigest,
      });
      expect(JSON.stringify(config)).not.toContain("private-material");
      expect(process.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("JIT target rejects a historical-shaped current Version without an explicit historical selector", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-jit-no-selector-"));
    const authorityTarget = {
      ...target,
      integrationE2eCredentialAuthority: {
        organizationId: INTEGRATION_E2E_ORGANIZATION_ID,
        publicJwk: { kty: "OKP", crv: "Ed25519", x: "E".repeat(43) },
      },
    } satisfies DeployTarget;
    try {
      const process = fixture({ diff: "src/auth.ts\n" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        authorityTarget,
        {
          ...process,
          outputDirectory: root,
          review: "reviewer@example.test",
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          signingDatabase: signingDatabase(`${"F".repeat(42)}A`),
        },
      ).catch((error) => error);

      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("does not declare the TAKOSERVER_ENVIRONMENT binding");
      expect(process.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("JIT target rejects wrong provenance exactly once without retrying through a stripped target", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-jit-wrong-provenance-"));
    const authorityTarget = {
      ...target,
      integrationE2eCredentialAuthority: {
        organizationId: INTEGRATION_E2E_ORGANIZATION_ID,
        publicJwk: { kty: "OKP", crv: "Ed25519", x: "E".repeat(43) },
      },
    } satisfies DeployTarget;
    try {
      const process = fixture({ diff: "src/catalog.ts\n" });
      const base = process.state;
      let workerVersionReads = 0;
      const state: WorkerState = {
        ...base,
        async workerVersion(workerName, versionId) {
          if (versionId !== VERSION_BEFORE) return await base.workerVersion(workerName, versionId);
          workerVersionReads += 1;
          const value = versionForTarget(
            versionId,
            `takoserver-worker:${LIVE_COMMIT}:${"c".repeat(64)}`,
            authorityTarget,
          );
          const source = value.resources.bindings.find(
            (binding) => binding.name === "TAKOSERVER_SOURCE_COMMIT",
          ) as { readonly name: string; readonly type: string; text?: string } | undefined;
          if (!source) throw new Error("missing JIT source binding");
          source.text = OTHER_COMMIT;
          return value;
        },
      };
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        authorityTarget,
        {
          ...process,
          state,
          outputDirectory: root,
          review: "reviewer@example.test",
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          signingDatabase: signingDatabase(`${"F".repeat(42)}A`),
        },
      ).catch((error) => error);

      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("binds TAKOSERVER_SOURCE_COMMIT with unexpected text");
      expect(workerVersionReads).toBe(1);
      expect(process.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("refuses JIT authority reuse of the active D1 signing key before any upload or put", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-jit-signing-reuse-"));
    const authorityTarget = {
      ...target,
      integrationE2eCredentialAuthority: {
        organizationId: INTEGRATION_E2E_ORGANIZATION_ID,
        publicJwk: { kty: "OKP", crv: "Ed25519", x: "E".repeat(43) },
      },
    } satisfies DeployTarget;
    try {
      const process = fixture({ diff: "src/auth.ts\n" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        authorityTarget,
        {
          ...process,
          outputDirectory: root,
          review: "reviewer@example.test",
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          signingDatabase: signingDatabase(
            authorityTarget.integrationE2eCredentialAuthority.publicJwk.x,
          ),
        },
      ).catch((error) => error);

      expect(failure).toMatchObject({ phase: "preflight" });
      expect(failure.message).toContain("must not reuse the active runtime signing key");
      expect(process.calls).toHaveLength(0);
      expect(process.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
      expect(process.calls.filter((call) => call.includes("put"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("integration authority cutover can bootstrap an exact unannotated predecessor", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-"));
    try {
      const current = fixture({
        beforeMessage: null,
        dirty: " M src/catalog.ts\0",
        legacyBeforeWithoutVersionMetadata: true,
      });
      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      );
      expect(result).toMatchObject({
        predecessorIdentity: "legacy-unattributed-predecessor",
        authorityScope: "entire-worker-artifact",
        legacyPredecessorVersionId: VERSION_BEFORE,
        changedPaths: null,
        authorityPaths: null,
        worktreePaths: ["src/catalog.ts"],
      });
      expect(current.calls.some((call) => call.join(" ").includes("git diff"))).toBe(false);
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(1);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(1);

      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({ deployedCommit: COMMIT, commitMatches: true });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status reports that the exact legacy predecessor remains current", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-current-"));
    try {
      const current = fixture({
        beforeMessage: null,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({
        kind: "takoserver.worker-status@v2",
        legacyPredecessorVersionId: VERSION_BEFORE,
        cutoverState: "legacy-predecessor-current",
        deployedCommit: null,
        artifactDigest: null,
        commitMatches: false,
        ready: false,
        versionId: VERSION_BEFORE,
        previousVersionId: null,
        predecessorIdentity: "legacy-unattributed-predecessor",
        authorityScope: "entire-worker-artifact",
      });
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(0);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status preserves canonical identity but never marks a pre-metadata predecessor ready", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-canonical-status-"));
    try {
      const current = fixture({
        beforeMessage: `takoserver-worker:${COMMIT}:${"c".repeat(64)}`,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({
        kind: "takoserver.worker-status@v2",
        legacyPredecessorVersionId: VERSION_BEFORE,
        cutoverState: "legacy-predecessor-current",
        deployedCommit: COMMIT,
        artifactDigest: `sha256:${"c".repeat(64)}`,
        commitMatches: true,
        ready: false,
        versionId: VERSION_BEFORE,
        authorityScope: "entire-worker-artifact",
      });
      expect(status).not.toHaveProperty("predecessorIdentity");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("integration authority cutover bootstraps a canonical pre-metadata predecessor as one artifact", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-canonical-apply-"));
    try {
      const current = fixture({
        dirty: " M src/catalog.ts\0",
        legacyBeforeWithoutVersionMetadata: true,
      });
      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      );
      expect(result).toMatchObject({
        authorityScope: "entire-worker-artifact",
        legacyPredecessorVersionId: VERSION_BEFORE,
        changedPaths: null,
        authorityPaths: null,
        worktreePaths: ["src/catalog.ts"],
        previousVersionId: VERSION_BEFORE,
        versionId: VERSION_AFTER,
      });
      expect(result).not.toHaveProperty("predecessorIdentity");
      expect(current.calls.some((call) => call.join(" ").includes("git diff"))).toBe(false);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status rejects an unattributed predecessor with the successor metadata binding", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-new-binding-"));
    try {
      const current = fixture({ beforeMessage: null });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("canonical annotation inventory");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status requires the direct successor to add version metadata", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-successor-binding-"));
    try {
      const current = fixture({
        current: "after",
        afterMessage: `takoserver-worker:${COMMIT}:${"f".repeat(64)}`,
        afterWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("does not declare the WORKER_VERSION binding");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status reconciles a lost upload acknowledgement to the selected commit", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-lost-ack-"));
    try {
      const current = fixture({
        current: "after",
        afterMessage: `takoserver-worker:${COMMIT}:${"f".repeat(64)}`,
      });
      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({
        kind: "takoserver.worker-status@v2",
        legacyPredecessorVersionId: VERSION_BEFORE,
        cutoverState: "selected-commit-current",
        deployedCommit: COMMIT,
        commitMatches: true,
        artifactDigest: `sha256:${"f".repeat(64)}`,
        ready: true,
        versionId: VERSION_AFTER,
        previousVersionId: VERSION_BEFORE,
      });
      expect(status).not.toHaveProperty("predecessorIdentity");
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(0);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status reports a direct advance to a different canonical commit", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-different-"));
    try {
      const current = fixture({
        current: "after",
        afterMessage: `takoserver-worker:${OTHER_COMMIT}:${"e".repeat(64)}`,
      });
      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({
        legacyPredecessorVersionId: VERSION_BEFORE,
        cutoverState: "different-commit-current",
        deployedCommit: OTHER_COMMIT,
        commitMatches: false,
        ready: false,
        versionId: VERSION_AFTER,
        previousVersionId: VERSION_BEFORE,
      });
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status rejects an unrelated canonical advancement", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-unrelated-"));
    try {
      const current = fixture({ current: "unrelated" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("not the direct successor");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("selector status rejects a malformed direct successor", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-status-malformed-"));
    try {
      const current = fixture({ current: "after", afterMessage: "not-canonical" });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("non-canonical annotation inventory");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("apply rejects an already advanced selector before its gate or upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-apply-advanced-"));
    try {
      const current = fixture({
        current: "after",
        afterMessage: `takoserver-worker:${COMMIT}:${"f".repeat(64)}`,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("does not match the pinned legacy predecessor");
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(0);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap rechecks the pinned predecessor after build and before upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-race-"));
    try {
      const current = fixture({
        beforeMessage: null,
        advanceDuringBuild: true,
        afterMessage: `takoserver-worker:${OTHER_COMMIT}:${"e".repeat(64)}`,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("pinned legacy predecessor");
      expect(current.calls.filter((call) => call.join(" ") === "bun run check")).toHaveLength(1);
      expect(current.calls.filter((call) => call.includes("--dry-run"))).toHaveLength(1);
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap rejects identity and binding-profile transition before upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-attribution-race-"));
    try {
      const current = fixture({
        beforeMessage: null,
        beforeMessageAfterBuild: `takoserver-worker:${LIVE_COMMIT}:${"c".repeat(64)}`,
        legacyBeforeWithoutVersionMetadata: true,
        beforeVersionMetadataAfterBuild: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("identity or binding profile changed");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("canonical legacy bootstrap rejects identity drift before upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-canonical-race-"));
    try {
      const current = fixture({
        beforeMessageAfterBuild: `takoserver-worker:${OTHER_COMMIT}:${"e".repeat(64)}`,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("identity or binding profile changed");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap rejects a same-Version deployment replacement during final inspection", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-history-race-"));
    try {
      const current = fixture({
        legacyBeforeWithoutVersionMetadata: true,
        replaceDeploymentDuringFinalInspection: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("deployment history changed during closure inspection");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap rechecks exact live closure immediately before upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-closure-race-"));
    try {
      const current = fixture({
        beforeMessage: null,
        secretsAfterBuild: [],
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("preflight");
      expect(failure.message).toContain("Worker secret inventory drift");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("an explicit selector does not downgrade a canonical predecessor", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-canonical-"));
    try {
      const current = fixture();
      const status = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      );
      expect(status).toMatchObject({
        deployedCommit: LIVE_COMMIT,
        commitMatches: false,
        ready: true,
        artifactDigest: `sha256:${"c".repeat(64)}`,
        versionId: VERSION_BEFORE,
      });
      expect(status).not.toHaveProperty("cutoverState");
      expect(status).not.toHaveProperty("predecessorIdentity");
      expect(status).not.toHaveProperty("legacyPredecessorVersionId");

      const result = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      );
      expect(result).toMatchObject({
        changedPaths: ["src/catalog.ts"],
        authorityPaths: [],
      });
      expect(result).not.toHaveProperty("predecessorIdentity");
      expect(result).not.toHaveProperty("authorityScope");
      expect(current.calls.some((call) => call.join(" ").includes("git diff"))).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap refuses an unannotated predecessor without the exact selector", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-no-selector-"));
    try {
      const current = fixture({
        beforeMessage: null,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("canonical annotation");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
      expect(current.calls.some((call) => call.includes("--no-bundle"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap refuses a selector that does not match the current Version", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-mismatch-"));
    try {
      const current = fixture({
        beforeMessage: null,
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: "00000000-0000-4000-8000-000000000099",
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("does not match the pinned legacy predecessor");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
      expect(current.calls.some((call) => call.includes("--no-bundle"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap requires an independent reviewer before its gate or upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-review-"));
    try {
      const current = fixture({
        beforeMessage: "not-canonical",
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.message).toContain("TAKOSERVER_INDEPENDENT_REVIEW");
      expect(current.calls.some((call) => call.join(" ") === "bun run check")).toBe(false);
      expect(current.calls.some((call) => call.includes("--no-bundle"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("legacy bootstrap never accepts a malformed annotation after upload", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-post-"));
    try {
      const current = fixture({
        beforeMessage: null,
        afterMessage: "not-canonical",
        legacyBeforeWithoutVersionMetadata: true,
      });
      const failure = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      ).catch((error) => error);
      expect(failure).toBeInstanceOf(DeployError);
      expect(failure.phase).toBe("verification");
      expect(failure.message).toContain("non-canonical annotation inventory");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("an advanced malformed Version cannot be re-adopted with the old selector", async () => {
    const root = mkdtempSync(join(tmpdir(), "takoserver-worker-legacy-advanced-"));
    try {
      const current = fixture({
        beforeMessage: null,
        afterMessage: "not-canonical",
        legacyBeforeWithoutVersionMetadata: true,
      });
      const first = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "apply",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          review: "reviewer@example.test",
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
          fetcher: publishedProductFetcher(),
        },
      ).catch((error) => error);
      expect(first).toBeInstanceOf(DeployError);
      expect(first.phase).toBe("verification");

      const second = await runWorker(
        {
          surface: "takoserver-worker-authority-cutover",
          action: "status",
          environment: "integration",
          commit: COMMIT,
          legacyPredecessorVersionId: VERSION_BEFORE,
        },
        target,
        {
          ...current,
          outputDirectory: root,
          cloudflareEnvironment: { CLOUDFLARE_API_TOKEN: "token" },
        },
      ).catch((error) => error);
      expect(second).toBeInstanceOf(DeployError);
      expect(second.message).toContain("non-canonical annotation inventory");
      expect(current.calls.filter((call) => call.includes("--no-bundle"))).toHaveLength(1);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

function publishedProductFetcher(
  options: { readonly discoveryOrigin?: string; readonly openApiOrigin?: string } = {},
) {
  const discoveryOrigin = options.discoveryOrigin ?? target.publicOrigin;
  const openApiOrigin = options.openApiOrigin ?? target.publicOrigin;
  return async (input: string): Promise<Response> => {
    const pathname = new URL(input).pathname;
    if (pathname === "/.well-known/takoserver") {
      return Response.json({
        product: "takoserver",
        apiVersion: "v1",
        endpoints: {
          api: discoveryOrigin,
          openapi: `${discoveryOrigin}/openapi.json`,
        },
      });
    }
    if (pathname === "/openapi.json") {
      return Response.json({ servers: [{ url: openApiOrigin }] });
    }
    return Response.json({ error: "not_found" }, { status: 404 });
  };
}

function deployment(id: string, versionId: string, created: string) {
  return {
    id,
    created_on: created,
    versions: [{ version_id: versionId, percentage: 100 }],
  };
}

function version(
  id: string,
  message: string | null,
  bindingProfile: "current" | "legacy-pre-version-metadata" = "current",
) {
  const expected = expectedExactBindingClosure(target);
  return {
    id,
    ...(message === null
      ? {}
      : {
          annotations: {
            "workers/message": message,
            "workers/triggered_by": "version_upload",
          },
        }),
    resources: {
      bindings: Object.entries(expected).flatMap(([name, requirement]) => {
        if (requirement === null) return [];
        if (bindingProfile === "legacy-pre-version-metadata" && name === "WORKER_VERSION") {
          return [];
        }
        return [{ name, type: requirement.type, ...requirement.fields }];
      }),
    },
  };
}

function versionForTarget(id: string, message: string, selectedTarget: DeployTarget) {
  const match = /^takoserver-worker:([0-9a-f]{40}):([0-9a-f]{64})$/u.exec(message);
  if (!match) throw new Error("invalid test Worker annotation");
  const expected = expectedExactBindingClosure(selectedTarget, {
    ...(selectedTarget.integrationE2eCredentialAuthority === undefined
      ? {}
      : {
          authorityProfile: {
            kind: "provenance-bound-jit" as const,
            provenance: {
              sourceCommit: match[1] as string,
              artifactDigest: `sha256:${match[2]}` as const,
            },
          },
        }),
  });
  return {
    id,
    annotations: {
      "workers/message": message,
      "workers/triggered_by": "version_upload",
    },
    resources: {
      bindings: Object.entries(expected).flatMap(([name, requirement]) =>
        requirement === null ? [] : [{ name, type: requirement.type, ...requirement.fields }],
      ),
    },
  };
}

function signingDatabase(publicX: string) {
  return {
    async readKey(keyId: string) {
      return {
        keyId,
        publicJwk: JSON.stringify({ kty: "OKP", crv: "Ed25519", x: publicX }),
        createdAtEpochSeconds: 1_700_000_000,
        revokedAtEpochSeconds: null,
      };
    },
  };
}

function ok(stdout: string): CommandResult {
  return { exitCode: 0, stdout, stderr: "" };
}
