import { Database, type SQLQueryBindings } from "bun:sqlite";
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { MIGRATIONS } from "../src/db-schema.ts";

const OPERATION_GENERATION = "0060_takoform_operation_generation.sql";
const IMPORT_SELECTION_MIGRATION = "0062_takoform_import_provider_selection.sql";
const IMPORT_SELECTION = JSON.stringify({
  version: "takoserver.takoform-import-selection@v1",
  kind: "intrinsic",
  nativeId: "native-import",
});

function applyMigration(database: Database, name: string, sql: string): void {
  database.exec("BEGIN IMMEDIATE");
  try {
    for (const statement of splitStatements(sql.replace(/^\s*--.*$/gmu, ""))) {
      database.exec(statement);
    }
    database
      .query("INSERT INTO applied_migrations (name, applied_at) VALUES (?, 'fixture')")
      .run(name);
    database.exec("COMMIT");
  } catch (error) {
    database.exec("ROLLBACK");
    throw error;
  }
}

function splitStatements(sql: string): readonly string[] {
  const statements: string[] = [];
  let rest = sql.trim();
  while (rest.length > 0) {
    if (/^CREATE\s+TRIGGER\b/iu.test(rest)) {
      const end = /^END\s*;/imu.exec(rest);
      if (!end) throw new Error("incomplete trigger fixture");
      const boundary = (end.index ?? 0) + end[0].length;
      statements.push(rest.slice(0, boundary).trim());
      rest = rest.slice(boundary).trim();
      continue;
    }
    const boundary = rest.indexOf(";");
    if (boundary < 0) {
      statements.push(rest);
      break;
    }
    const statement = rest.slice(0, boundary).trim();
    if (statement.length > 0) statements.push(statement);
    rest = rest.slice(boundary + 1).trim();
  }
  return statements;
}

function migrationSql(): string {
  return readFileSync(
    resolve(import.meta.dir, "../migrations", IMPORT_SELECTION_MIGRATION),
    "utf8",
  );
}

function createDatabaseBeforeImportSelection(): Database {
  const database = new Database(":memory:");
  database.exec("PRAGMA foreign_keys = ON");
  database.exec(`
    CREATE TABLE applied_migrations (
      name TEXT PRIMARY KEY NOT NULL,
      applied_at TEXT NOT NULL
    );
  `);
  const operationGenerationIndex = MIGRATIONS.findIndex(
    (migration) => migration.name === OPERATION_GENERATION,
  );
  expect(operationGenerationIndex).toBeGreaterThan(0);
  for (const migration of MIGRATIONS.slice(0, operationGenerationIndex + 2)) {
    applyMigration(database, migration.name, migration.sql);
  }
  return database;
}

function createDatabaseAtImportSelection(): Database {
  const database = new Database(":memory:");
  database.exec("PRAGMA foreign_keys = ON");
  database.exec(`
    CREATE TABLE applied_migrations (
      name TEXT PRIMARY KEY NOT NULL,
      applied_at TEXT NOT NULL
    );
  `);

  const operationGenerationIndex = MIGRATIONS.findIndex(
    (migration) => migration.name === OPERATION_GENERATION,
  );
  const importSelectionIndex = MIGRATIONS.findIndex(
    (migration) => migration.name === IMPORT_SELECTION_MIGRATION,
  );
  expect(operationGenerationIndex).toBeGreaterThan(0);
  expect(importSelectionIndex === -1 || importSelectionIndex > operationGenerationIndex).toBe(true);
  for (const migration of MIGRATIONS.slice(0, operationGenerationIndex)) {
    applyMigration(database, migration.name, migration.sql);
  }
  seedLegacySaga(database);

  const generatedImportMigrationIndex =
    importSelectionIndex < 0 ? MIGRATIONS.length : importSelectionIndex;
  for (const migration of MIGRATIONS.slice(
    operationGenerationIndex,
    generatedImportMigrationIndex,
  )) {
    applyMigration(database, migration.name, migration.sql);
  }
  seedGenerationSagas(database);
  // Read the migration file itself so this fixture exercises the exact DDL;
  // db-schema.ts is regenerated by the owning schema lane.
  applyMigration(database, IMPORT_SELECTION_MIGRATION, migrationSql());
  insertCurrentImportSaga(database);
  return database;
}

function seedLegacySaga(database: Database): void {
  database
    .query(
      `INSERT INTO tf_provider_mutation_sagas (
         operation_id, replay_key, tenant_id, fingerprint, resource_uid,
         target_space, target_api_version, target_kind, target_name,
         accepted_uid, accepted_generation, accepted_revision, phase,
         receipt_json, created_at, updated_at, expires_at,
         execution_lease_token, execution_lease_until, execution_started_at,
         provider_outcome
       ) VALUES (
         'legacy-saga', 'legacy-replay', 'tenant-legacy', 'legacy-fingerprint',
         'legacy-resource', 'main', 'edge.forms.takoform.com', 'Thing', 'legacy',
         NULL, NULL, NULL, 'planned', NULL, 100, 100, 999999,
         'legacy-lease', 500, 150, 'indeterminate'
       )`,
    )
    .run();
}

function seedGenerationSagas(database: Database): void {
  // Only terminal historical import rows may pass the 0062 quiescence guard;
  // their NULL marker remains preserved as evidence.
  insertGenerationSaga(database, "old-null-import", "import", 150, "executed");
  insertGenerationSaga(database, "dispatched-import", "import", 150, "executed");
  insertGenerationSaga(database, "apply-row", "apply");
  insertGenerationSaga(database, "delete-row", "delete");
}

function insertGenerationSaga(
  database: Database,
  operationId: string,
  operationKind: "apply" | "import" | "delete",
  executionStartedAt: number | null = null,
  phase: "planned" | "executed" = "planned",
): void {
  const leaseToken = executionStartedAt === null ? null : `lease-${operationId}`;
  const providerOutcome = phase === "executed" ? "indeterminate" : "planned";
  const receiptJson = phase === "executed" ? "{}" : null;
  const expiresAt = phase === "executed" ? null : 999999;
  const values: SQLQueryBindings[] = [
    operationId,
    1,
    operationKind,
    `replay-${operationId}`,
    "tenant-current",
    `fingerprint-${operationId}`,
    `resource-${operationId}`,
    "main",
    "edge.forms.takoform.com",
    "Thing",
    operationId,
    null,
    null,
    null,
    phase,
    receiptJson,
    100,
    100,
    expiresAt,
    null,
    leaseToken,
    executionStartedAt === null ? null : 500,
    executionStartedAt,
    null,
    providerOutcome,
    null,
    null,
  ];
  database
    .query(
      `INSERT INTO tf_provider_mutation_sagas_selection_v1 (
         operation_id, protocol_generation, operation_kind, replay_key, tenant_id,
         fingerprint, resource_uid, target_space, target_api_version, target_kind,
         target_name, accepted_uid, accepted_generation, accepted_revision, phase,
         receipt_json, created_at, updated_at, expires_at, authority_head_digest,
         execution_lease_token, execution_lease_until, execution_started_at,
         provider_handle, provider_outcome, selection_json,
         selection_verified_lease_token
       ) VALUES (${values.map(() => "?").join(", ")})`,
    )
    .run(...values);
}

function setLease(database: Database, operationId: string, leaseToken: string): void {
  database
    .query(
      `UPDATE tf_provider_mutation_sagas_selection_v1
       SET execution_lease_token = ?, execution_lease_until = 5000
       WHERE operation_id = ?`,
    )
    .run(leaseToken, operationId);
}

function insertCurrentImportSaga(database: Database, operationId = "new-import"): void {
  database
    .query(
      `INSERT INTO tf_provider_mutation_sagas_selection_v1 (
         operation_id, protocol_generation, operation_kind, replay_key, tenant_id,
         fingerprint, resource_uid, target_space, target_api_version, target_kind,
         target_name, accepted_uid, accepted_generation, accepted_revision, phase,
         receipt_json, created_at, updated_at, expires_at, authority_head_digest,
         execution_lease_token, execution_lease_until, execution_started_at,
         provider_handle, provider_outcome, selection_json,
         selection_verified_lease_token, import_selection_protocol
       ) VALUES (?, 1, 'import', ?, 'tenant-current', ?, ?, 'main',
                 'edge.forms.takoform.com', 'Thing', ?, NULL, NULL, NULL,
                 'planned', NULL, 100, 100, 999999, NULL, NULL, NULL, NULL,
                 NULL, 'planned', NULL, NULL, 1)`,
    )
    .run(
      operationId,
      `replay-${operationId}`,
      `fingerprint-${operationId}`,
      `resource-${operationId}`,
      operationId,
    );
}

describe("Takoform import provider-selection schema migration", () => {
  test("refuses a planned pre-0062 import atomically before adding any column", () => {
    const database = createDatabaseBeforeImportSelection();
    try {
      insertGenerationSaga(database, "planned-old-import", "import");
      expect(() => applyMigration(database, IMPORT_SELECTION_MIGRATION, migrationSql())).toThrow(
        "takoform_provider_mutation_import_selection_migration_requires_quiescence",
      );
      expect(
        database
          .query("SELECT name FROM applied_migrations WHERE name = ?")
          .get(IMPORT_SELECTION_MIGRATION),
      ).toBeNull();
      expect(
        database
          .query(
            "SELECT COUNT(*) AS n FROM pragma_table_info('tf_provider_mutation_sagas_selection_v1') WHERE name = 'import_selection_protocol'",
          )
          .get(),
      ).toEqual({ n: 0 });
      expect(
        database
          .query(
            `SELECT phase, receipt_json FROM tf_provider_mutation_sagas_selection_v1
             WHERE operation_id = 'planned-old-import'`,
          )
          .get(),
      ).toEqual({ phase: "planned", receipt_json: null });
    } finally {
      database.close();
    }
  });

  test("adds import proof columns without rewriting legacy NULL rows", () => {
    const database = createDatabaseAtImportSelection();
    try {
      expect(
        database
          .query(
            `SELECT import_selection_json, import_selection_verified_lease_token,
                    import_selection_protocol, phase, receipt_json
             FROM tf_provider_mutation_sagas_selection_v1
             WHERE operation_id = 'old-null-import'`,
          )
          .get(),
      ).toEqual({
        import_selection_json: null,
        import_selection_verified_lease_token: null,
        import_selection_protocol: null,
        phase: "executed",
        receipt_json: "{}",
      });
      expect(
        database
          .query(
            `SELECT selection_json, selection_verified_lease_token
             FROM tf_provider_mutation_sagas WHERE operation_id = 'legacy-saga'`,
          )
          .get(),
      ).toEqual({ selection_json: null, selection_verified_lease_token: null });
      expect(
        database.query("SELECT name FROM applied_migrations ORDER BY rowid").all().at(-1),
      ).toEqual({ name: IMPORT_SELECTION_MIGRATION });
    } finally {
      database.close();
    }
  });

  test("binds import once, dispatches with the exact lease, and preserves apply/delete", () => {
    const database = createDatabaseAtImportSelection();
    try {
      setLease(database, "new-import", "import-lease");
      expect(
        database
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ?, import_selection_verified_lease_token = ?
             WHERE operation_id = 'new-import' AND execution_started_at IS NULL`,
          )
          .run(IMPORT_SELECTION, "import-lease").changes,
      ).toBe(1);
      expect(
        database
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET execution_started_at = 200, provider_outcome = 'running'
             WHERE operation_id = 'new-import'`,
          )
          .run().changes,
      ).toBe(1);

      setLease(database, "apply-row", "apply-lease");
      expect(
        database
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET selection_json = ?, selection_verified_lease_token = ?
             WHERE operation_id = 'apply-row'`,
          )
          .run(IMPORT_SELECTION, "apply-lease").changes,
      ).toBe(1);
      expect(
        database
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET execution_started_at = 210, provider_outcome = 'running'
             WHERE operation_id = 'apply-row'`,
          )
          .run().changes,
      ).toBe(1);

      setLease(database, "delete-row", "delete-lease");
      expect(
        database
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET execution_started_at = 220, provider_outcome = 'running'
             WHERE operation_id = 'delete-row'`,
          )
          .run().changes,
      ).toBe(1);
    } finally {
      database.close();
    }
  });

  test("old cleanup cannot erase a bound import before dispatch or under an unverified recovery lease", () => {
    const database = createDatabaseAtImportSelection();
    try {
      setLease(database, "new-import", "import-lease");
      database
        .query(`UPDATE tf_provider_mutation_sagas_selection_v1
        SET import_selection_json = ?, import_selection_verified_lease_token = 'import-lease'
        WHERE operation_id = 'new-import'`)
        .run(IMPORT_SELECTION);
      database
        .query(`UPDATE tf_provider_mutation_sagas_selection_v1
        SET execution_lease_token = NULL, execution_lease_until = NULL
        WHERE operation_id = 'new-import'`)
        .run();
      expect(() =>
        database
          .query(`DELETE FROM tf_provider_mutation_sagas_selection_v1
        WHERE tenant_id = ? AND operation_id = ? AND replay_key = ? AND resource_uid = ?
          AND protocol_generation = 1 AND phase = 'planned' AND receipt_json IS NULL
          AND execution_lease_token IS NULL AND execution_started_at IS NULL`)
          .run("tenant-current", "new-import", "replay-new-import", "resource-new-import"),
      ).toThrow("takoform_provider_mutation_import_selection_retained_constraint");
      setLease(database, "new-import", "import-lease");
      database
        .query(`UPDATE tf_provider_mutation_sagas_selection_v1
        SET execution_started_at = 200, provider_outcome = 'running'
        WHERE operation_id = 'new-import'`)
        .run();
      setLease(database, "new-import", "old-recovery-lease");
      const oldDefinitiveDelete =
        database.query(`DELETE FROM tf_provider_mutation_sagas_selection_v1
        WHERE tenant_id = ? AND operation_id = ? AND replay_key = ? AND resource_uid = ?
          AND protocol_generation = 1 AND operation_kind = 'import'
          AND phase = 'planned' AND receipt_json IS NULL
          AND execution_lease_token = ? AND execution_lease_until > ?
          AND execution_started_at IS NOT NULL`);
      expect(() =>
        oldDefinitiveDelete.run(
          "tenant-current",
          "new-import",
          "replay-new-import",
          "resource-new-import",
          "old-recovery-lease",
          200,
        ),
      ).toThrow("takoform_provider_mutation_import_selection_retained_constraint");
      database
        .query(`UPDATE tf_provider_mutation_sagas_selection_v1
        SET import_selection_verified_lease_token = 'old-recovery-lease'
        WHERE operation_id = 'new-import'`)
        .run();
      expect(
        oldDefinitiveDelete.run(
          "tenant-current",
          "new-import",
          "replay-new-import",
          "resource-new-import",
          "old-recovery-lease",
          200,
        ).changes,
      ).toBe(1);
    } finally {
      database.close();
    }
  });

  test("rejects missing, forged, late, mutated, oversized, and foreign-kind import proof", () => {
    const missing = createDatabaseAtImportSelection();
    try {
      expect(() =>
        missing
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET execution_started_at = 200
             WHERE operation_id = 'new-import'`,
          )
          .run(),
      ).toThrow("takoform_provider_mutation_import_selection_unverified_constraint");
    } finally {
      missing.close();
    }

    const forged = createDatabaseAtImportSelection();
    try {
      setLease(forged, "new-import", "import-lease");
      forged
        .query(
          `UPDATE tf_provider_mutation_sagas_selection_v1
           SET import_selection_json = ?, import_selection_verified_lease_token = 'forged-lease'
           WHERE operation_id = 'new-import'`,
        )
        .run(IMPORT_SELECTION);
      expect(() =>
        forged
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET execution_started_at = 200
             WHERE operation_id = 'new-import'`,
          )
          .run(),
      ).toThrow("takoform_provider_mutation_import_selection_unverified_constraint");
    } finally {
      forged.close();
    }

    const late = createDatabaseAtImportSelection();
    try {
      expect(() =>
        late
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ?
             WHERE operation_id = 'dispatched-import'`,
          )
          .run(IMPORT_SELECTION),
      ).toThrow("takoform_provider_mutation_import_selection_immutable");
      expect(() =>
        late
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ?, import_selection_verified_lease_token = ?,
                 execution_started_at = NULL
             WHERE operation_id = 'dispatched-import'`,
          )
          .run(IMPORT_SELECTION, "lease-dispatched-import"),
      ).toThrow("takoform_provider_mutation_import_selection_immutable");
    } finally {
      late.close();
    }

    const mutation = createDatabaseAtImportSelection();
    try {
      setLease(mutation, "new-import", "import-lease");
      mutation
        .query(
          `UPDATE tf_provider_mutation_sagas_selection_v1
           SET import_selection_json = ?, import_selection_verified_lease_token = ?
           WHERE operation_id = 'new-import'`,
        )
        .run(IMPORT_SELECTION, "import-lease");
      expect(() =>
        mutation
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ? WHERE operation_id = 'new-import'`,
          )
          .run(JSON.stringify({ changed: true })),
      ).toThrow("takoform_provider_mutation_import_selection_immutable");

      expect(() =>
        mutation
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_verified_lease_token = 'token'
             WHERE operation_id = 'new-import'`,
          )
          .run(),
      ).not.toThrow();
    } finally {
      mutation.close();
    }

    const constraints = createDatabaseAtImportSelection();
    try {
      expect(() =>
        constraints
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_verified_lease_token = 'token'
             WHERE operation_id = 'new-import'`,
          )
          .run(),
      ).toThrow("CHECK constraint failed");
      expect(() =>
        constraints
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ? WHERE operation_id = 'apply-row'`,
          )
          .run(IMPORT_SELECTION),
      ).toThrow("CHECK constraint failed");
      expect(() =>
        constraints
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_verified_lease_token = 'token'
             WHERE operation_id = 'delete-row'`,
          )
          .run(),
      ).toThrow("CHECK constraint failed");
      expect(() =>
        constraints
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = '[]' WHERE operation_id = 'new-import'`,
          )
          .run(),
      ).toThrow("CHECK constraint failed");
      expect(() =>
        constraints
          .query(
            `UPDATE tf_provider_mutation_sagas_selection_v1
             SET import_selection_json = ? WHERE operation_id = 'new-import'`,
          )
          .run(JSON.stringify({ value: "x".repeat(131072) })),
      ).toThrow("CHECK constraint failed");
    } finally {
      constraints.close();
    }
  });

  test("requires and immutably retains the new protocol marker", () => {
    const database = createDatabaseAtImportSelection();
    try {
      expect(
        database
          .query(
            `SELECT import_selection_protocol FROM tf_provider_mutation_sagas_selection_v1
             WHERE operation_id = 'new-import'`,
          )
          .get(),
      ).toEqual({ import_selection_protocol: 1 });
      expect(() => insertGenerationSaga(database, "old-writer-import", "import")).toThrow(
        "takoform_provider_mutation_import_selection_protocol_required",
      );
      expect(
        database
          .query(
            `SELECT COUNT(*) AS n FROM tf_provider_mutation_sagas_selection_v1
             WHERE operation_id = 'old-writer-import'`,
          )
          .get(),
      ).toEqual({ n: 0 });
      for (const value of [null, 2]) {
        expect(() =>
          database
            .query(
              `UPDATE tf_provider_mutation_sagas_selection_v1
               SET import_selection_protocol = ? WHERE operation_id = 'new-import'`,
            )
            .run(value),
        ).toThrow("takoform_provider_mutation_import_selection_protocol_immutable");
      }
    } finally {
      database.close();
    }
  });
});
