-- Dormant private Takoform Host admission state.
--
-- These tables are deliberately separate from the customer Resource and
-- artifact lanes.  Every row is an append-only event: the predecessor and
-- event digests form a chain, while unique indexes turn a predecessor or
-- sequence into a one-writer fence.  Runtime/public composition is a later
-- wave and must not be inferred from this schema alone.

CREATE TABLE tf_form_publisher_events (
  id TEXT PRIMARY KEY NOT NULL,
  publisher_key TEXT NOT NULL,
  event_type TEXT NOT NULL,
  policy_digest TEXT NOT NULL,
  policy_json TEXT NOT NULL,
  oidc_issuer TEXT NOT NULL,
  source_repository TEXT NOT NULL,
  workflow TEXT NOT NULL,
  ref TEXT NOT NULL,
  publisher_identity TEXT NOT NULL,
  source_commit TEXT NOT NULL,
  workflow_commit TEXT NOT NULL,
  repository_identifier TEXT NOT NULL,
  owner_identifier TEXT NOT NULL,
  namespace_group TEXT NOT NULL,
  namespace_grant_digest TEXT NOT NULL,
  trusted_root_digest TEXT NOT NULL,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (event_type IN ('allow', 'rotate', 'deny')),
  CHECK (length(id) BETWEEN 3 AND 255),
  CHECK (length(publisher_key) BETWEEN 1 AND 255),
  CHECK (length(policy_digest) = 71 AND substr(policy_digest, 1, 7) = 'sha256:' AND substr(policy_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid(policy_json)),
  CHECK (length(oidc_issuer) BETWEEN 1 AND 2048),
  CHECK (length(source_repository) BETWEEN 1 AND 512),
  CHECK (length(workflow) BETWEEN 1 AND 512),
  CHECK (length(ref) BETWEEN 1 AND 512),
  CHECK (length(publisher_identity) BETWEEN 1 AND 1024),
  CHECK (length(source_commit) BETWEEN 1 AND 256),
  CHECK (length(workflow_commit) BETWEEN 1 AND 256),
  CHECK (length(repository_identifier) BETWEEN 1 AND 256),
  CHECK (length(owner_identifier) BETWEEN 1 AND 256),
  CHECK (length(namespace_group) BETWEEN 1 AND 255),
  CHECK (length(namespace_grant_digest) = 71 AND substr(namespace_grant_digest, 1, 7) = 'sha256:' AND substr(namespace_grant_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(trusted_root_digest) = 71 AND substr(trusted_root_digest, 1, 7) = 'sha256:' AND substr(trusted_root_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (publisher_key, event_digest),
  UNIQUE (publisher_key, predecessor_digest)
);

CREATE INDEX tf_form_publisher_head_lookup
  ON tf_form_publisher_events (publisher_key, event_at, id);

CREATE TABLE tf_form_revocation_checkpoints (
  id TEXT PRIMARY KEY NOT NULL,
  publisher_key TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  checkpoint_digest TEXT NOT NULL,
  entries_digest TEXT NOT NULL,
  previous_checkpoint_digest TEXT NOT NULL,
  revoked_package_digests_json TEXT NOT NULL,
  policy_digest TEXT NOT NULL,
  policy_event_digest TEXT NOT NULL,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (length(id) BETWEEN 3 AND 255),
  CHECK (length(publisher_key) BETWEEN 1 AND 255),
  CHECK (sequence > 0),
  CHECK (length(checkpoint_digest) = 71 AND substr(checkpoint_digest, 1, 7) = 'sha256:' AND substr(checkpoint_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(entries_digest) = 71 AND substr(entries_digest, 1, 7) = 'sha256:' AND substr(entries_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(previous_checkpoint_digest) = 71 AND substr(previous_checkpoint_digest, 1, 7) = 'sha256:' AND substr(previous_checkpoint_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid(revoked_package_digests_json) AND json_type(revoked_package_digests_json) = 'array'),
  CHECK (length(policy_digest) = 71 AND substr(policy_digest, 1, 7) = 'sha256:' AND substr(policy_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(policy_event_digest) = 71 AND substr(policy_event_digest, 1, 7) = 'sha256:' AND substr(policy_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (publisher_key, sequence),
  UNIQUE (publisher_key, event_digest),
  UNIQUE (publisher_key, predecessor_digest)
);

CREATE INDEX tf_form_revocation_checkpoint_head_lookup
  ON tf_form_revocation_checkpoints (publisher_key, sequence, event_at, id);

CREATE TABLE tf_form_install_events (
  id TEXT PRIMARY KEY NOT NULL,
  form_ref_key TEXT NOT NULL,
  form_ref_json TEXT NOT NULL,
  form_api_version TEXT NOT NULL,
  form_kind TEXT NOT NULL,
  form_definition_version TEXT NOT NULL,
  schema_digest TEXT NOT NULL,
  package_digest TEXT NOT NULL,
  event_type TEXT NOT NULL,
  replaces_package_digest TEXT,
  admission_report_digest TEXT NOT NULL,
  admission_report_json TEXT NOT NULL,
  publisher_key TEXT NOT NULL,
  policy_digest TEXT NOT NULL,
  policy_event_digest TEXT NOT NULL,
  checkpoint_sequence INTEGER NOT NULL,
  checkpoint_digest TEXT NOT NULL,
  checkpoint_event_digest TEXT NOT NULL,
  source_commit TEXT NOT NULL,
  workflow_commit TEXT NOT NULL,
  repository_identifier TEXT NOT NULL,
  owner_identifier TEXT NOT NULL,
  namespace_group TEXT NOT NULL,
  namespace_grant_digest TEXT NOT NULL,
  implementation_digest TEXT,
  retention_ref TEXT,
  retention_until INTEGER,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (event_type IN ('install', 'replace', 'uninstall')),
  CHECK (length(id) BETWEEN 3 AND 255),
  CHECK (length(form_ref_key) BETWEEN 1 AND 255),
  CHECK (json_valid(form_ref_json)),
  CHECK (length(form_api_version) BETWEEN 1 AND 255),
  CHECK (length(form_kind) BETWEEN 1 AND 255),
  CHECK (length(form_definition_version) BETWEEN 1 AND 255),
  CHECK (length(schema_digest) = 71 AND substr(schema_digest, 1, 7) = 'sha256:' AND substr(schema_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(package_digest) = 71 AND substr(package_digest, 1, 7) = 'sha256:' AND substr(package_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (replaces_package_digest IS NULL OR (length(replaces_package_digest) = 71 AND substr(replaces_package_digest, 1, 7) = 'sha256:' AND substr(replaces_package_digest, 8) NOT GLOB '*[^0-9a-f]*')),
  CHECK (length(admission_report_digest) = 71 AND substr(admission_report_digest, 1, 7) = 'sha256:' AND substr(admission_report_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid(admission_report_json)),
  CHECK (length(publisher_key) BETWEEN 1 AND 255),
  CHECK (length(policy_digest) = 71 AND substr(policy_digest, 1, 7) = 'sha256:' AND substr(policy_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(policy_event_digest) = 71 AND substr(policy_event_digest, 1, 7) = 'sha256:' AND substr(policy_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (checkpoint_sequence > 0),
  CHECK (length(checkpoint_digest) = 71 AND substr(checkpoint_digest, 1, 7) = 'sha256:' AND substr(checkpoint_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(checkpoint_event_digest) = 71 AND substr(checkpoint_event_digest, 1, 7) = 'sha256:' AND substr(checkpoint_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(source_commit) BETWEEN 1 AND 256),
  CHECK (length(workflow_commit) BETWEEN 1 AND 256),
  CHECK (length(repository_identifier) BETWEEN 1 AND 256),
  CHECK (length(owner_identifier) BETWEEN 1 AND 256),
  CHECK (length(namespace_group) BETWEEN 1 AND 255),
  CHECK (length(namespace_grant_digest) = 71 AND substr(namespace_grant_digest, 1, 7) = 'sha256:' AND substr(namespace_grant_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (implementation_digest IS NULL OR (length(implementation_digest) = 71 AND substr(implementation_digest, 1, 7) = 'sha256:' AND substr(implementation_digest, 8) NOT GLOB '*[^0-9a-f]*')),
  CHECK (retention_until IS NULL OR retention_until >= 0),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (form_ref_key, event_digest),
  UNIQUE (form_ref_key, predecessor_digest)
);

CREATE INDEX tf_form_install_package_lookup
  ON tf_form_install_events (package_digest, form_ref_key, event_at, id);

CREATE INDEX tf_form_install_head_lookup
  ON tf_form_install_events (form_ref_key, event_at, id);

CREATE TABLE tf_form_support_events (
  id TEXT PRIMARY KEY NOT NULL,
  support_key TEXT NOT NULL,
  form_ref_key TEXT NOT NULL,
  form_ref_json TEXT NOT NULL,
  package_digest TEXT NOT NULL,
  supported INTEGER NOT NULL,
  profile_json TEXT NOT NULL,
  operations_json TEXT NOT NULL,
  implementation_digest TEXT NOT NULL,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (supported IN (0, 1)),
  CHECK (json_valid(form_ref_json)),
  CHECK (length(package_digest) = 71 AND substr(package_digest, 1, 7) = 'sha256:' AND substr(package_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid(profile_json)),
  CHECK (json_valid(operations_json) AND json_type(operations_json) = 'array'),
  CHECK (length(implementation_digest) = 71 AND substr(implementation_digest, 1, 7) = 'sha256:' AND substr(implementation_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (support_key, event_digest),
  UNIQUE (support_key, predecessor_digest)
);

CREATE INDEX tf_form_support_package_lookup
  ON tf_form_support_events (package_digest, support_key, event_at, id);

CREATE TABLE tf_form_activation_events (
  id TEXT PRIMARY KEY NOT NULL,
  activation_key TEXT NOT NULL,
  form_ref_key TEXT NOT NULL,
  form_ref_json TEXT NOT NULL,
  package_digest TEXT NOT NULL,
  audience_kind TEXT NOT NULL,
  audience_value TEXT NOT NULL,
  active INTEGER NOT NULL,
  implementation_digest TEXT NOT NULL,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (active IN (0, 1)),
  CHECK (audience_kind IN ('host', 'tenant', 'space', 'principal')),
  CHECK (length(audience_value) BETWEEN 1 AND 255),
  CHECK (json_valid(form_ref_json)),
  CHECK (length(package_digest) = 71 AND substr(package_digest, 1, 7) = 'sha256:' AND substr(package_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(implementation_digest) = 71 AND substr(implementation_digest, 1, 7) = 'sha256:' AND substr(implementation_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (activation_key, event_digest),
  UNIQUE (activation_key, predecessor_digest)
);

CREATE INDEX tf_form_activation_package_lookup
  ON tf_form_activation_events (package_digest, activation_key, event_at, id);

CREATE TABLE tf_form_evacuation_events (
  id TEXT PRIMARY KEY NOT NULL,
  resource_uid TEXT NOT NULL,
  form_ref_key TEXT NOT NULL,
  form_ref_json TEXT NOT NULL,
  package_digest TEXT NOT NULL,
  implementation_digest TEXT NOT NULL,
  event_type TEXT NOT NULL,
  claim TEXT NOT NULL,
  progress_json TEXT NOT NULL,
  receipt_json TEXT,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (length(resource_uid) BETWEEN 3 AND 255),
  CHECK (json_valid(form_ref_json)),
  CHECK (length(package_digest) = 71 AND substr(package_digest, 1, 7) = 'sha256:' AND substr(package_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(implementation_digest) = 71 AND substr(implementation_digest, 1, 7) = 'sha256:' AND substr(implementation_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (event_type IN ('pending', 'settled')),
  CHECK (length(claim) BETWEEN 1 AND 1024),
  CHECK (json_valid(progress_json)),
  CHECK (receipt_json IS NULL OR json_valid(receipt_json)),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (resource_uid, event_digest),
  UNIQUE (resource_uid, predecessor_digest)
);

CREATE INDEX tf_form_evacuation_package_lookup
  ON tf_form_evacuation_events (package_digest, resource_uid, event_at, id);

-- Package garbage-collection is its own chain.  It never appends a
-- `purge-pending`/`purged` successor to the install chain, so a retained
-- superseded package can be cleaned up without moving the current install
-- head.  The source install event pins the full policy/checkpoint/report
-- evidence needed to audit the deletion decision.
CREATE TABLE tf_form_package_purge_events (
  id TEXT PRIMARY KEY NOT NULL,
  form_ref_key TEXT NOT NULL,
  form_ref_json TEXT NOT NULL,
  form_api_version TEXT NOT NULL,
  form_kind TEXT NOT NULL,
  form_definition_version TEXT NOT NULL,
  schema_digest TEXT NOT NULL,
  package_digest TEXT NOT NULL,
  implementation_digest TEXT,
  publisher_key TEXT NOT NULL,
  policy_digest TEXT NOT NULL,
  policy_event_digest TEXT NOT NULL,
  checkpoint_sequence INTEGER NOT NULL,
  checkpoint_digest TEXT NOT NULL,
  checkpoint_event_digest TEXT NOT NULL,
  source_commit TEXT NOT NULL,
  workflow_commit TEXT NOT NULL,
  repository_identifier TEXT NOT NULL,
  owner_identifier TEXT NOT NULL,
  namespace_group TEXT NOT NULL,
  namespace_grant_digest TEXT NOT NULL,
  admission_report_digest TEXT NOT NULL,
  admission_report_json TEXT NOT NULL,
  retention_ref TEXT,
  retention_until INTEGER,
  event_type TEXT NOT NULL,
  source_install_event_digest TEXT NOT NULL,
  actor TEXT NOT NULL,
  reason TEXT NOT NULL,
  event_at INTEGER NOT NULL,
  event_digest TEXT NOT NULL,
  predecessor_digest TEXT NOT NULL,
  CHECK (event_type IN ('purge-pending', 'purged')),
  CHECK (length(id) BETWEEN 3 AND 255),
  CHECK (length(form_ref_key) BETWEEN 1 AND 255),
  CHECK (json_valid(form_ref_json)),
  CHECK (length(form_api_version) BETWEEN 1 AND 255),
  CHECK (length(form_kind) BETWEEN 1 AND 255),
  CHECK (length(form_definition_version) BETWEEN 1 AND 255),
  CHECK (length(schema_digest) = 71 AND substr(schema_digest, 1, 7) = 'sha256:' AND substr(schema_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(package_digest) = 71 AND substr(package_digest, 1, 7) = 'sha256:' AND substr(package_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (implementation_digest IS NULL OR (length(implementation_digest) = 71 AND substr(implementation_digest, 1, 7) = 'sha256:' AND substr(implementation_digest, 8) NOT GLOB '*[^0-9a-f]*')),
  CHECK (length(publisher_key) BETWEEN 1 AND 255),
  CHECK (length(policy_digest) = 71 AND substr(policy_digest, 1, 7) = 'sha256:' AND substr(policy_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(policy_event_digest) = 71 AND substr(policy_event_digest, 1, 7) = 'sha256:' AND substr(policy_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (checkpoint_sequence > 0),
  CHECK (length(checkpoint_digest) = 71 AND substr(checkpoint_digest, 1, 7) = 'sha256:' AND substr(checkpoint_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(checkpoint_event_digest) = 71 AND substr(checkpoint_event_digest, 1, 7) = 'sha256:' AND substr(checkpoint_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(source_commit) BETWEEN 1 AND 256),
  CHECK (length(workflow_commit) BETWEEN 1 AND 256),
  CHECK (length(repository_identifier) BETWEEN 1 AND 256),
  CHECK (length(owner_identifier) BETWEEN 1 AND 256),
  CHECK (length(namespace_group) BETWEEN 1 AND 255),
  CHECK (length(namespace_grant_digest) = 71 AND substr(namespace_grant_digest, 1, 7) = 'sha256:' AND substr(namespace_grant_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(admission_report_digest) = 71 AND substr(admission_report_digest, 1, 7) = 'sha256:' AND substr(admission_report_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (json_valid(admission_report_json)),
  CHECK (retention_until IS NULL OR retention_until >= 0),
  CHECK (length(source_install_event_digest) = 71 AND substr(source_install_event_digest, 1, 7) = 'sha256:' AND substr(source_install_event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(actor) BETWEEN 1 AND 255),
  CHECK (length(reason) BETWEEN 1 AND 4096),
  CHECK (event_at >= 0),
  CHECK (length(event_digest) = 71 AND substr(event_digest, 1, 7) = 'sha256:' AND substr(event_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  CHECK (length(predecessor_digest) = 71 AND substr(predecessor_digest, 1, 7) = 'sha256:' AND substr(predecessor_digest, 8) NOT GLOB '*[^0-9a-f]*'),
  UNIQUE (form_ref_key, package_digest, event_digest),
  UNIQUE (form_ref_key, package_digest, predecessor_digest)
);

CREATE INDEX tf_form_package_purge_lookup
  ON tf_form_package_purge_events (form_ref_key, package_digest, event_at, id);
