import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const ENTRYPOINT = resolve(ROOT, "src/workflow-http-bootstrap-entry.ts");
const OUTPUT = resolve(ROOT, "src/generated/workflow-http-bootstrap.ts");
const WRAPPER_SOURCE = resolve(ROOT, "src/providers/selfhost-worker-wrapper.ts");
const PROJECT_ENV_EXPORT = "__takoserverSelfhostProjectEnv";

const arguments_ = process.argv.slice(2);
const check = arguments_.includes("--check");
const write = arguments_.includes("--write");
if (arguments_.some((argument) => argument !== "--check" && argument !== "--write")) {
  throw new Error("workflow HTTP bootstrap generator accepts only --write or --check");
}
if (check === write) {
  throw new Error("workflow HTTP bootstrap generator requires exactly one of --write or --check");
}

const source = await bundleHostBootstrap();
const digest = `sha256:${createHash("sha256").update(source, "utf8").digest("hex")}`;
const generated = renderGenerated(source, digest);

if (check) {
  let actual: string;
  try {
    actual = readFileSync(OUTPUT, "utf8");
  } catch {
    throw new Error("workflow HTTP bootstrap artifact is missing; run --write");
  }
  if (actual !== generated) {
    throw new Error("workflow HTTP bootstrap artifact is stale; run --write");
  }
} else {
  writeFileSync(OUTPUT, generated, "utf8");
}

async function bundleHostBootstrap(): Promise<string> {
  assertProjectEnvExport();
  const built = await Bun.build({
    entrypoints: [ENTRYPOINT],
    root: ROOT,
    target: "browser",
    format: "esm",
    minify: false,
    splitting: false,
    sourcemap: "none",
  });
  if (!built.success) {
    for (const log of built.logs) console.error(log);
    throw new Error("workflow HTTP bootstrap bundle failed");
  }
  if (built.outputs.length !== 1) {
    throw new Error("workflow HTTP bootstrap bundle produced an unexpected output count");
  }
  const output = built.outputs[0];
  if (output === undefined) throw new Error("workflow HTTP bootstrap bundle output is missing");
  let source = await output.text();
  if (!source.endsWith("\n")) source += "\n";

  // The Host helper must be a closed ESM bundle. Dynamic imports are deliberate
  // (the wrapper and application arrive only on RUN), but no static import may
  // remain for Bun or any source outside this Host-owned graph.
  if (
    /^\s*(?:import\s+(?:["'][^"']+["']|.+?\s+from\s+["'])|export\s+.+?\s+from\s+["'])/mu.test(
      source,
    )
  ) {
    throw new Error("workflow HTTP bootstrap bundle contains a static external import");
  }
  const dynamicImportCount = source.match(/\bimport\s*\(/gu)?.length ?? 0;
  if (!source.includes("createWorkflowHttpBootstrap") || dynamicImportCount !== 2) {
    throw new Error("workflow HTTP bootstrap bundle lost its factory or dynamic imports");
  }
  return source;
}

function assertProjectEnvExport(): void {
  const wrapper = readFileSync(WRAPPER_SOURCE, "utf8");
  const declaration = wrapper.match(
    /export const SELFHOST_WORKER_PROJECT_ENV_EXPORT = "([^"]+)" as const;/u,
  );
  if (declaration?.[1] !== PROJECT_ENV_EXPORT) {
    throw new Error("workflow HTTP bootstrap project environment export drifted");
  }
}

function renderGenerated(source: string, digest: string): string {
  return `${[
    "// Code generated by scripts/generate-workflow-http-bootstrap.ts. DO NOT EDIT.",
    "// This is the deterministic Host-only ESM bundle for private Workflow execution.",
    "",
    "// biome-ignore format: Keep deterministic JSON string serialization for the artifact check.",
    `export const WORKFLOW_HTTP_BOOTSTRAP_SOURCE =`,
    "// biome-ignore lint/suspicious/noTemplateCurlyInString: Bundled JavaScript is data, not a template.",
    `  ${JSON.stringify(source)} as const;`,
    `export const WORKFLOW_HTTP_BOOTSTRAP_DIGEST =\n  ${JSON.stringify(digest)} as const;`,
    "",
  ].join("\n")}`;
}
