/**
 * Projects the closed portable error taxonomy out of Takoform's frozen Host API
 * operations spec.
 *
 * The table this writes used to be a hand-kept literal in `src/error-envelope.ts`
 * carrying a sentence — "Keep this table equal to `internal/clientv3/errors.go`'s
 * `stableErrorHTTPStatusByCode`" — as its only tie to the released provider that
 * decodes it. A sentence is not a mechanism: nothing read both, and a Host that
 * drifts answers a well-formed envelope the provider reads as an opaque
 * rejection rather than as the classification the route meant.
 *
 * The spec file is vendored under `vendor/takoform/host-api-v1/` and pinned by
 * size and SHA-256 to an exact takoform tag and commit, the same way the Form
 * corpus is pinned, so both this Host and the Go client answer to one artifact
 * neither of them wrote.
 *
 *   bun scripts/generate-stable-error-taxonomy.ts          # write
 *   bun scripts/generate-stable-error-taxonomy.ts --check  # refuse on drift
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

const VENDOR_ROOT = "vendor/takoform/host-api-v1";
const MANIFEST_PATH = `${VENDOR_ROOT}/source-manifest.json`;
const MANIFEST_SIZE = 415;
const MANIFEST_SHA256 = "bd64d5d256866542e347da639d9031475df1b2008800229050fd6e58f6ab1a99";
const GENERATED_PATH = "src/generated/takoform-stable-error-taxonomy.ts";

interface SourceManifest {
  readonly format: "takoserver.vendored-takoform-source@v1";
  readonly repository: string;
  readonly tag: string;
  readonly commit: string;
  readonly files: readonly {
    readonly local: string;
    readonly source: string;
    readonly size: number;
    readonly sha256: string;
  }[];
}

const manifestBytes = readFileSync(MANIFEST_PATH);
if (
  manifestBytes.byteLength !== MANIFEST_SIZE ||
  createHash("sha256").update(manifestBytes).digest("hex") !== MANIFEST_SHA256
) {
  throw new Error("takoform_host_api_source_manifest_mismatch");
}
const manifest = JSON.parse(manifestBytes.toString("utf8")) as SourceManifest;
if (
  manifest.format !== "takoserver.vendored-takoform-source@v1" ||
  manifest.repository !== "https://github.com/tako0614/takoform.git" ||
  manifest.tag !== "v1.1.0" ||
  manifest.commit !== "e0e48b864de2a127a255cb0574d37bbb0f1cac29" ||
  manifest.files.length !== 1
) {
  throw new Error("takoform_host_api_source_authority_mismatch");
}

const declared = manifest.files[0];
if (declared === undefined || declared.source !== "spec/host-api/operations-v1.json") {
  throw new Error("takoform_host_api_source_file_mismatch");
}
const specBytes = readFileSync(`${VENDOR_ROOT}/${declared.local}`);
if (
  specBytes.byteLength !== declared.size ||
  createHash("sha256").update(specBytes).digest("hex") !== declared.sha256
) {
  throw new Error("takoform_host_api_spec_bytes_mismatch");
}

const spec = JSON.parse(specBytes.toString("utf8")) as {
  readonly errorEnvelope?: {
    readonly codes?: readonly string[];
    readonly automaticallyRetryable?: readonly string[];
    readonly httpStatusByCode?: Readonly<Record<string, number>>;
  };
};
const envelope = spec.errorEnvelope;
const codes = envelope?.codes;
const retryable = envelope?.automaticallyRetryable;
const statusByCode = envelope?.httpStatusByCode;
if (codes === undefined || retryable === undefined || statusByCode === undefined) {
  throw new Error("takoform_host_api_error_envelope_missing");
}
// The spec states the closed set twice; a Host that trusted only one of them
// would not notice the other moving.
const statusCodes = Object.keys(statusByCode);
if (statusCodes.length !== codes.length || codes.some((code) => !(code in statusByCode))) {
  throw new Error("takoform_host_api_error_code_set_disagrees_with_status_map");
}
if (retryable.some((code) => !(code in statusByCode))) {
  throw new Error("takoform_host_api_retryable_code_outside_taxonomy");
}

const rendered = `${[
  "// Generated by scripts/generate-stable-error-taxonomy.ts. Do not edit.",
  "//",
  `// Source: ${manifest.repository} ${manifest.tag} (${manifest.commit})`,
  `//         ${declared.source}, sha256:${declared.sha256}`,
  "//",
  "// The closed portable taxonomy of the stable Takoform Host lane. The released",
  "// provider's `parseAPIError` decodes exactly these code/status pairs; anything",
  "// else it reads as an opaque rejection rather than a classification.",
  "",
  "/** The closed portable code set, and the one status each code is answered at. */",
  "export const STABLE_ERROR_HTTP_STATUS: Readonly<Record<string, number>> = Object.freeze({",
  ...codes.map((code) => `  ${code}: ${statusByCode[code]},`),
  "});",
  "",
  "/** The only codes a Host may mark `retryable: true`. */",
  "export const AUTOMATICALLY_RETRYABLE_ERROR_CODES: readonly string[] = Object.freeze([",
  ...retryable.map((code) => `  "${code}",`),
  "]);",
].join("\n")}\n`;

if (process.argv.includes("--check")) {
  const actual = readFileSync(GENERATED_PATH, "utf8");
  if (actual !== rendered) {
    console.error(
      `${GENERATED_PATH} is stale; run \`bun scripts/generate-stable-error-taxonomy.ts\``,
    );
    process.exit(1);
  }
} else {
  await Bun.write(GENERATED_PATH, rendered);
}
