import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { bytesDigest, canonicalDigest, canonicalJson, isJsonObject } from "../src/json.ts";
import { currentTakoformCandidates } from "../src/takoform/current-candidates.ts";
import {
  YURUCOMMU_FORM_VERSIONS,
  yurucommuFormCandidates,
} from "../src/takoform/implementation-catalog.ts";

const ROOT = resolve(import.meta.dir, "..");
const FIXTURE_ROOT = resolve(
  ROOT,
  "tests/fixtures/takoform-v1/forms/candidates/edge.forms.takoform.com",
);
const OUTPUT = resolve(ROOT, "src/generated/takoform-integration-form-packages.ts");
const check = process.argv.includes("--check");

interface Candidate {
  readonly kind: string;
  readonly path: string;
  readonly formRef: Record<string, unknown>;
  readonly packageDigest: string;
}

interface PackageFile {
  readonly path: string;
  readonly digest: string;
  readonly size: number;
  readonly mediaType?: string;
}

const candidateSet = JSON.parse(
  readFileSync(resolve(FIXTURE_ROOT, "candidate-set.json"), "utf8"),
) as { readonly forms?: readonly Candidate[] };
if (!Array.isArray(candidateSet.forms)) throw new Error("edge candidate set is malformed");

const generated = [];
const verifiedCandidates = yurucommuFormCandidates(currentTakoformCandidates().forms);
for (const form of verifiedCandidates) {
  const kind = form.identity.formRef.kind;
  const definitionVersion = YURUCOMMU_FORM_VERSIONS[kind as keyof typeof YURUCOMMU_FORM_VERSIONS];
  const matches = candidateSet.forms.filter(
    (candidate) =>
      candidate.kind === kind &&
      candidate.formRef.definitionVersion === definitionVersion &&
      canonicalJson(candidate.formRef) === canonicalJson(form.identity.formRef) &&
      candidate.packageDigest === form.identity.packageDigest,
  );
  const candidate = matches[0];
  if (matches.length !== 1 || !candidate) {
    throw new Error(`exact generated package candidate is missing: ${kind}`);
  }
  const packageRoot = resolve(ROOT, "tests/fixtures/takoform-v1", candidate.path);
  if (!packageRoot.startsWith(`${FIXTURE_ROOT}/`)) {
    throw new Error(`package path escaped the verified fixture root: ${kind}`);
  }
  const manifest = JSON.parse(
    readFileSync(resolve(packageRoot, "package-index.json"), "utf8"),
  ) as Record<string, unknown>;
  if (
    !isJsonObject(manifest) ||
    canonicalJson(manifest.formRef) !== canonicalJson(form.identity.formRef) ||
    (await canonicalDigest(manifest)) !== form.identity.packageDigest ||
    !Array.isArray(manifest.files)
  ) {
    throw new Error(`verified package manifest drifted: ${kind}`);
  }
  const files = [];
  for (const descriptor of manifest.files as unknown as readonly PackageFile[]) {
    if (
      !descriptor ||
      typeof descriptor.path !== "string" ||
      typeof descriptor.digest !== "string" ||
      !Number.isSafeInteger(descriptor.size)
    ) {
      throw new Error(`verified package file descriptor is malformed: ${kind}`);
    }
    const path = resolve(packageRoot, descriptor.path);
    if (!path.startsWith(`${packageRoot}/`)) {
      throw new Error(`package payload path escaped its root: ${kind}`);
    }
    const bytes = readFileSync(path);
    if (bytes.byteLength !== descriptor.size || (await bytesDigest(bytes)) !== descriptor.digest) {
      throw new Error(`verified package payload drifted: ${kind}/${descriptor.path}`);
    }
    files.push({
      path: descriptor.path,
      digest: descriptor.digest,
      ...(descriptor.mediaType === undefined ? {} : { mediaType: descriptor.mediaType }),
      base64: bytes.toString("base64"),
    });
  }
  generated.push({
    packageDigest: form.identity.packageDigest,
    formRef: form.identity.formRef,
    manifest,
    files,
  });
}

const source = `${[
  "// Code generated by scripts/generate-integration-form-packages.ts. DO NOT EDIT.",
  "// This unsigned corpus is usable only through the integration-fixture adapter.",
  "",
  `export const INTEGRATION_FORM_PACKAGES = ${JSON.stringify(generated, null, 2)} as const;`,
  "",
].join("\n")}`;
const formatted = execFileSync(
  process.execPath,
  ["x", "biome", "format", "--stdin-file-path", OUTPUT],
  { cwd: ROOT, input: source, encoding: "utf8", maxBuffer: 8 * 1024 * 1024 },
);

if (check) {
  if (readFileSync(OUTPUT, "utf8") !== formatted) {
    throw new Error("integration Form package corpus is stale");
  }
} else {
  writeFileSync(OUTPUT, formatted);
}
