import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const OUTER_ENTRYPOINT = resolve(ROOT, "src/workflow-loader-outer-entry.ts");
const TENANT_ENTRYPOINT = resolve(ROOT, "src/workflow-loader-tenant-entry.ts");
const OUTPUT = resolve(ROOT, "src/generated/workflow-loader-bootstrap.ts");

const arguments_ = process.argv.slice(2);
const check = arguments_.includes("--check");
const write = arguments_.includes("--write");
if (arguments_.some((argument) => argument !== "--check" && argument !== "--write")) {
  throw new Error("workflow loader bootstrap generator accepts only --write or --check");
}
if (check === write) {
  throw new Error("workflow loader bootstrap generator requires exactly one of --write or --check");
}

const outer = await bundle(OUTER_ENTRYPOINT, "outer");
const tenant = await bundle(TENANT_ENTRYPOINT, "tenant");
const generated = renderGenerated(outer, tenant);

if (check) {
  let actual: string;
  try {
    actual = readFileSync(OUTPUT, "utf8");
  } catch {
    throw new Error("workflow loader bootstrap artifact is missing; run --write");
  }
  if (actual !== generated) {
    throw new Error("workflow loader bootstrap artifact is stale; run --write");
  }
} else {
  writeFileSync(OUTPUT, generated, "utf8");
}

async function bundle(entrypoint: string, label: "outer" | "tenant"): Promise<string> {
  const built = await Bun.build({
    entrypoints: [entrypoint],
    root: ROOT,
    target: "browser",
    format: "esm",
    minify: false,
    splitting: false,
    sourcemap: "none",
    external: ["cloudflare:workers"],
  });
  if (!built.success) {
    for (const log of built.logs) console.error(log);
    throw new Error(`workflow loader ${label} bootstrap bundle failed`);
  }
  if (built.outputs.length !== 1) {
    throw new Error(
      `workflow loader ${label} bootstrap bundle produced an unexpected output count`,
    );
  }
  const output = built.outputs[0];
  if (output === undefined) throw new Error(`workflow loader ${label} bootstrap output is missing`);
  let source = await output.text();
  if (!source.endsWith("\n")) source += "\n";

  // Only the trusted outer may import workerd's WorkerEntrypoint intrinsic.
  // The closed tenant bootstrap uses functional RPC and cannot import builtins.
  // Tenant application imports remain dynamic in the WorkerLoader graph.
  const staticImports = [
    ...source.matchAll(/(?:^|\n)\s*import\s+(?:[^\n;]+\s+from\s+)?["']([^"']+)["']/gu),
  ].map((match) => match[1]);
  if (staticImports.some((specifier) => label !== "outer" || specifier !== "cloudflare:workers")) {
    throw new Error(`workflow loader ${label} bootstrap has an unexpected static import`);
  }
  if (label === "outer") {
    if (!source.includes("createWorkflowLoaderOuterBootstrap")) {
      throw new Error("workflow loader outer bootstrap lost its factory");
    }
    if ((source.match(/\bimport\s*\(/gu) ?? []).length !== 0) {
      throw new Error("workflow loader outer bootstrap must not import tenant code");
    }
  } else if (
    !source.includes("createWorkflowLoaderTenantBootstrap") ||
    (source.match(/\bimport\s*\(/gu) ?? []).length !== 2
  ) {
    throw new Error("workflow loader tenant bootstrap lost its two dynamic imports");
  }
  return source;
}

function renderGenerated(outer: string, tenant: string): string {
  const outerDigest = `sha256:${createHash("sha256").update(outer, "utf8").digest("hex")}`;
  const tenantDigest = `sha256:${createHash("sha256").update(tenant, "utf8").digest("hex")}`;
  return `${[
    "// Code generated by scripts/generate-workflow-loader-bootstrap.ts. DO NOT EDIT.",
    "// These are deterministic Host-only ESM bundles for private Workflow execution.",
    "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Bundled JavaScript is data, not a template.",
    "",
    "// biome-ignore format: Keep deterministic JSON string serialization for the artifact check.",
    `export const WORKFLOW_LOADER_OUTER_SOURCE =\n  ${JSON.stringify(outer)} as const;`,
    `export const WORKFLOW_LOADER_OUTER_DIGEST =\n  ${JSON.stringify(outerDigest)} as const;`,
    "// biome-ignore format: Keep deterministic JSON string serialization for the artifact check.",
    `export const WORKFLOW_LOADER_TENANT_SOURCE =\n  ${JSON.stringify(tenant)} as const;`,
    `export const WORKFLOW_LOADER_TENANT_DIGEST =\n  ${JSON.stringify(tenantDigest)} as const;`,
    "",
  ].join("\n")}`;
}
