import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { loadFrozenStableCatalog } from "../src/worker-stable-local-composition.ts";

const EXPECTED_REPOSITORY = "https://github.com/tako0614/terraform-provider-takoform.git";
const EXPECTED_COMMIT = "a225cfa7c84aa551981cc8ad56c9a281fa6e051a";
const OUTPUT = resolve(import.meta.dir, "../src/generated/takoform-stable-v1-catalog.ts");

const source = resolve(requiredFlag("--source"));
const check = process.argv.includes("--check");
const commit = git(source, "rev-parse", "HEAD");
const repository = normalizeRepository(git(source, "remote", "get-url", "origin"));
if (commit !== EXPECTED_COMMIT || repository !== EXPECTED_REPOSITORY) {
  throw new Error("staging adoption catalog source identity drifted");
}
if (git(source, "status", "--porcelain", "--untracked-files=all") !== "") {
  throw new Error("staging adoption catalog source must be a clean exact commit");
}

const catalog = await loadFrozenStableCatalog(source);
const generated = `${[
  "// Code generated by scripts/generate-stable-production-catalog.ts. DO NOT EDIT.",
  "",
  `export const STABLE_PRODUCTION_TAKOFORM_CATALOG = ${JSON.stringify(
    {
      provenance: {
        repository,
        commit,
        familyIndexSha256: catalog.provenance.familyIndexSha256,
        familyCount: catalog.provenance.familyCount,
        formCount: catalog.provenance.formCount,
        bindingCount: catalog.provenance.bindingCount,
      },
      forms: catalog.forms,
      bindings: catalog.bindings,
    },
    null,
    2,
  )} as const;`,
  "",
].join("\n")}`;
const formatted = execFileSync(
  process.execPath,
  ["x", "biome", "format", "--stdin-file-path", OUTPUT],
  {
    cwd: resolve(import.meta.dir, ".."),
    input: generated,
    encoding: "utf8",
  },
);

if (check) {
  const existing = readFileSync(OUTPUT, "utf8");
  if (existing !== formatted) throw new Error("staging adoption catalog is stale");
} else {
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, formatted);
}

function requiredFlag(name: string): string {
  const index = process.argv.indexOf(name);
  const value = index < 0 ? undefined : process.argv[index + 1];
  if (!value || value.startsWith("--")) throw new Error(`missing ${name}`);
  return value;
}

function git(cwd: string, ...args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

function normalizeRepository(value: string): string {
  if (value === "git@github.com:tako0614/terraform-provider-takoform.git") {
    return EXPECTED_REPOSITORY;
  }
  return value;
}
