import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const args = process.argv.slice(2);
if (args.length !== 1 || (args[0] !== "--check" && args[0] !== "--write"))
  throw new Error("Selfhost Workflow Binding runtime source requires --check or --write");
const root = resolve(import.meta.dir, "..");
const output = resolve(root, "src/generated/selfhost-workflow-binding-runtime-source.ts");
const built = await Bun.build({
  entrypoints: [resolve(root, "src/selfhost-workflow-binding-runtime-entry.ts")],
  root,
  target: "browser",
  format: "esm",
  minify: false,
  splitting: false,
  sourcemap: "none",
});
if (!built.success || built.outputs.length !== 1 || !built.outputs[0])
  throw new Error("Selfhost Workflow Binding runtime source build failed");
const source = await built.outputs[0].text();
if (/^\s*(?:import\s|export\s+.+\s+from)/mu.test(source))
  throw new Error("Selfhost Workflow Binding runtime must be a closed bundle");
const digest = `sha256:${createHash("sha256").update(source).digest("hex")}`;
const generated = `// Generated by scripts/generate-selfhost-workflow-binding-runtime-source.ts. DO NOT EDIT.\n// biome-ignore format: deterministic artifact bytes\nexport const SELFHOST_WORKFLOW_BINDING_RUNTIME_SOURCE =\n// biome-ignore lint/suspicious/noTemplateCurlyInString: bundled source is data\n  ${JSON.stringify(source)} as const;\nexport const SELFHOST_WORKFLOW_BINDING_RUNTIME_DIGEST =\n  ${JSON.stringify(digest)} as const;\n`;
if (args[0] === "--write") writeFileSync(output, generated);
else if (readFileSync(output, "utf8") !== generated)
  throw new Error("Selfhost Workflow Binding runtime source stale; run generator --write");
