import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

/**
 * Generates `src/db-schema.ts` from the migration files.
 *
 * The `.sql` files stay canonical — they are what D1 applies in production —
 * but a self-hosted server and the test suite need the same schema without
 * reading the filesystem at runtime. Rather than maintain two definitions, the
 * TypeScript module is a checked build product, exactly like the OpenAPI
 * document.
 */

const repository = resolve(import.meta.dir, "..");
const directory = join(repository, "migrations");

export function renderSchemaModule(): string {
  const names = readdirSync(directory)
    .filter((name) => name.endsWith(".sql"))
    .sort();
  const migrations = names.map((name) => ({
    name,
    sql: readFileSync(join(directory, name), "utf8"),
  }));
  return `// Generated by \`bun run schema:write\` from migrations/*.sql. Do not edit.

export interface Migration {
  readonly name: string;
  readonly sql: string;
}

/** Every migration, in application order. */
export const MIGRATIONS: readonly Migration[] = ${JSON.stringify(migrations, null, 2)};
`;
}

if (import.meta.main) {
  writeFileSync(join(repository, "src/db-schema.ts"), renderSchemaModule());
}
