/**
 * The published API description.
 *
 * The literal stable Takoform Host lane is the only Host API described here.
 * Retired beta/alpha identities remain historical Takoform artifacts, never
 * current Takoserver routes. The document is a checked build product:
 * `openapi/takoserver.openapi.json` is regenerated by `bun run openapi:write`
 * and compared byte for byte in the gate.
 */

const TAKOFORM_LANES = ["v1"] as const;

/** Every Takoform Host path, relative to a lane mount. */
const TAKOFORM_PATHS: readonly {
  readonly path: string;
  readonly methods: readonly { readonly method: string; readonly summary: string }[];
}[] = [
  { path: "/forms", methods: [{ method: "get", summary: "Resolve one exact installed Form" }] },
  {
    path: "/form-definitions/{group}/{kind}",
    methods: [{ method: "get", summary: "Read an installed Form definition" }],
  },
  {
    path: "/support/forms",
    methods: [{ method: "get", summary: "List support profiles for installed Forms" }],
  },
  {
    path: "/support/forms/{group}/{kind}/{definitionVersion}",
    methods: [{ method: "get", summary: "Read one Form support profile" }],
  },
  {
    path: "/support/interfaces/{name}/{version}",
    methods: [{ method: "get", summary: "Read a provided Interface contract" }],
  },
  {
    path: "/support/bindings/{name}/{version}",
    methods: [{ method: "get", summary: "Read an accepted Binding contract" }],
  },
  {
    path: "/support/standard-services/{protocol}",
    methods: [{ method: "get", summary: "Read exact standard-service support" }],
  },
  {
    path: "/resources/validate",
    methods: [{ method: "post", summary: "Validate desired state without recording it" }],
  },
  {
    path: "/resources/prepare",
    methods: [{ method: "post", summary: "Review desired state and mint a prepare digest" }],
  },
  {
    path: "/resources/{group}/{kind}/{name}",
    methods: [
      { method: "get", summary: "Read a resource" },
      { method: "put", summary: "Apply reviewed desired state" },
      { method: "delete", summary: "Delete a resource" },
    ],
  },
  {
    path: "/resources/{group}/{kind}/{name}/observe",
    methods: [{ method: "post", summary: "Refresh observed state from the backend" }],
  },
  {
    path: "/resources/{group}/{kind}/{name}/import",
    methods: [{ method: "post", summary: "Adopt an existing native resource" }],
  },
  {
    path: "/operations/{operationId}",
    methods: [{ method: "get", summary: "Read a settled operation" }],
  },
  {
    path: "/operations/{operationId}/cancel",
    methods: [{ method: "post", summary: "Request cancellation of an operation" }],
  },
  {
    path: "/artifacts/uploads",
    methods: [{ method: "post", summary: "Start an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}",
    methods: [{ method: "delete", summary: "Abandon an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}/commit",
    methods: [{ method: "post", summary: "Commit an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}/blobs/{digest}",
    methods: [{ method: "put", summary: "Upload one declared blob" }],
  },
  {
    path: "/artifacts/{digest}",
    methods: [{ method: "get", summary: "Read a committed manifest" }],
  },
  {
    path: "/artifacts/blobs/{digest}",
    methods: [{ method: "head", summary: "Check whether a blob is held" }],
  },
];

const PUBLIC_PATHS: Record<string, Record<string, unknown>> = {
  "/": operation("get", "Console", { security: [] }),
  "/openapi.json": operation("get", "This document", { security: [] }),
  "/.well-known/takoserver": operation("get", "Product discovery", { security: [] }),
  "/.well-known/takoform/v1": operation("get", "Stable Takoform Host discovery", {
    security: [],
  }),
  "/v1/identity/providers": operation("get", "Identity providers accepted for sign-in", {
    security: [],
  }),
  "/v1/sessions": operation("post", "Exchange an external assertion for a session", {
    security: [],
  }),
  "/v1/me": operation("get", "Read the signed-in principal and the organizations it owns"),
  "/v1/ai/models": operation("get", "List configured OpenAI-compatible models"),
  "/v1/ai/chat/completions": operation(
    "post",
    "Create a prepaid OpenAI-compatible chat completion",
    {
      parameters: [
        {
          name: "Idempotency-Key",
          in: "header",
          required: true,
          schema: { type: "string", minLength: 1, maxLength: 128 },
          description: "Stable per paid inference; replays return the same settled result.",
        },
        {
          name: "X-Takoserver-AI-Pricing-Revision",
          in: "header",
          required: false,
          schema: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
          description:
            "Optional exact model pricing revision from /v1/ai/models; drift is rejected before inference.",
        },
      ],
    },
  ),
  "/v1/forms": operation("get", "List every Form definition this Host will accept", {
    security: [],
  }),
  "/v1/organizations": operation("post", "Create an Organization"),
  "/v1/organizations/{organizationId}/api-keys": operations({
    post: "Create a scoped API key",
    get: "List the organization's live API keys",
  }),
  "/v1/organizations/{organizationId}/resources": operation(
    "get",
    "List the organization's Takoform resources",
  ),
  "/v1/organizations/{organizationId}/resources/{resourceUid}": operation(
    "get",
    "Read one exact organization Takoform resource",
  ),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations": operations({
    get: "List explicit provider migrations for one logical Resource",
    post: "Plan a migration against an exact commercial reservation",
  }),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations/{migrationId}": operation(
    "get",
    "Read one Resource Migration",
  ),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations/{migrationId}/execute":
    operation("post", "Provision, transfer, and verify a candidate Deployment"),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations/{migrationId}/cutover":
    operation("post", "Atomically activate the candidate and re-resolve Attachments"),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations/{migrationId}/rollback":
    operation("post", "Restore the retained Deployment and Attachment resolutions"),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/migrations/{migrationId}/cancel":
    operation("post", "Delete an uncut candidate and release its commercial reservation"),
  "/v1/organizations/{organizationId}/attachments": operations({
    get: "List the organization's Resource Attachments",
    post: "Resolve and create a Resource Attachment",
  }),
  "/v1/organizations/{organizationId}/attachments/{attachmentId}": operations({
    get: "Read one Resource Attachment",
    delete: "Delete one Resource Attachment",
  }),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/s3-credentials": operation(
    "post",
    "Issue short-lived S3 credentials for a historical ObjectBucket record",
  ),
  "/v1/organizations/{organizationId}/operations": operation(
    "get",
    "List the organization's recent Takoform operations",
  ),
  "/v1/organizations/{organizationId}/api-keys/{apiKeyId}": operation(
    "delete",
    "Revoke an API key",
  ),
  "/v1/organizations/{organizationId}/wallet": operation("get", "Read the prepaid wallet"),
  "/v1/organizations/{organizationId}/wallet/checkout": operation(
    "post",
    "Begin a card payment for this organization",
  ),
  "/v1/organizations/{organizationId}/wallet/funding": operation(
    "post",
    "Credit the wallet from a verified settlement proof",
  ),
  "/v1/catalog": operation("get", "List purchasable offerings"),
  "/v1/reseller/quotes": operation("post", "Price an offering for a tenant"),
  "/v1/reseller/reservations": operation("post", "Reserve a quote, holding funds"),
  "/v1/reseller/reservations/{reservationId}/capture": operation(
    "post",
    "Capture a reservation against reported usage",
  ),
  "/v1/reseller/reservations/{reservationId}/release": operation(
    "post",
    "Release a reservation and return its hold",
  ),
  "/v1/reseller/reservations/{reservationId}/provision-tokens": operation(
    "post",
    "Mint a single-use provisioning token for a reservation",
  ),
  "/v1/reseller/reservations/{reservationId}/takoform-run-tokens": operation(
    "post",
    "Mint a short-lived exact-Resource bearer for an ordinary Takoform provider run",
  ),
  "/v1/reseller/reservations/{reservationId}/usage-statement": operation(
    "get",
    "Read the usage statement of a captured reservation",
  ),
};

/** One path that answers to more than one method. */
function operations(summaries: Readonly<Record<string, string>>): Record<string, unknown> {
  return Object.assign(
    {},
    ...Object.entries(summaries).map(([method, summary]) => operation(method, summary)),
  ) as Record<string, unknown>;
}

function operation(
  method: string,
  summary: string,
  extra: {
    readonly security?: readonly unknown[];
    readonly parameters?: readonly unknown[];
  } = {},
): Record<string, unknown> {
  return {
    [method]: {
      summary,
      responses: { "200": { description: "Success" } },
      ...(extra.security ? { security: extra.security } : {}),
      ...(extra.parameters ? { parameters: extra.parameters } : {}),
    },
  };
}

function takoformPaths(): Record<string, Record<string, unknown>> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const lane of TAKOFORM_LANES) {
    for (const entry of TAKOFORM_PATHS) {
      const methods: Record<string, unknown> = {};
      for (const { method, summary } of entry.methods) {
        methods[method] = { summary, responses: { "200": { description: "Success" } } };
      }
      paths[`/apis/forms.takoform.com/${lane}${entry.path}`] = methods;
    }
  }
  return paths;
}

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Takoserver API",
    version: "1.0.0",
    summary: "An independent prepaid platform for Takoform-declared resources.",
  },
  servers: [{ url: "https://api.takoserver.com" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description:
          "A session secret, an organization API key, or a resource-scoped token, " +
          "depending on the route.",
      },
    },
  },
  paths: { ...PUBLIC_PATHS, ...takoformPaths() },
} as const;

/**
 * Build the served document for one deployment. The checked artifact keeps the
 * stable production origin above, while each running deployment advertises the
 * public origin selected by its environment (or by an explicit local/test
 * composition).
 */
export function createOpenApiDocument(publicOrigin: string) {
  return { ...openApiDocument, servers: [{ url: publicOrigin }] };
}

/** Every path the document declares, sorted. Used by the contract test. */
export function openApiPaths(): readonly string[] {
  return Object.keys(openApiDocument.paths).sort();
}
