import {
  ARTIFACT_CONSUMER_REPAIR_APPLY_FORMAT,
  ARTIFACT_CONSUMER_REPAIR_STATUS_FORMAT,
  ARTIFACT_CONSUMER_RESOLUTION_RECEIPT_FORMAT,
} from "./artifact-consumer-repair.ts";
import { ROUTES, TAKOFORM_LANES, TAKOFORM_ROUTES, takoformRoutePattern } from "./route-table.ts";
import { SPACE_ID_MAX_CODE_POINTS, SPACE_ID_PATTERN_SOURCE } from "./takoform/space-id.ts";

/**
 * The published API description.
 *
 * The document is *projected* from `route-table.ts`: that table says which
 * routes exist, and the table below says what each one does. A route the table
 * declares and this file does not describe fails to build, and a description
 * no route names fails to build too — so the document can no longer be a
 * second, quietly divergent statement of the surface.
 *
 * The literal stable Takoform Host lane is the only Host API described here.
 * Retired beta/alpha identities remain historical Takoform artifacts, never
 * current Takoserver routes. The document is a checked build product:
 * `openapi/takoserver.openapi.json` is regenerated by `bun run openapi:write`
 * and compared byte for byte in the gate.
 */

/** Every Takoform Host route's published summary, by operation name. */
const TAKOFORM_OPERATION_SUMMARIES: Readonly<Record<string, string>> = {
  takoformResolveForm: "Resolve one exact installed Form",
  takoformReadFormDefinition: "Read an installed Form definition",
  takoformListSupportProfiles: "List support profiles for installed Forms",
  takoformReadSupportProfile: "Read one Form support profile",
  takoformReadInterfaceContract: "Read a provided Interface contract",
  takoformReadBindingContract: "Read an accepted Binding contract",
  takoformValidateResource: "Validate desired state without recording it",
  takoformPrepareResource: "Review desired state and mint a prepare digest",
  takoformReadResource: "Read a resource",
  takoformApplyResource: "Apply reviewed desired state",
  takoformDeleteResource: "Delete a resource",
  takoformObserveResource: "Refresh observed state from the backend",
  takoformImportResource: "Adopt an existing native resource",
  takoformReadOperation: "Read a settled operation",
  takoformCancelOperation: "Request cancellation of an operation",
  takoformStartArtifactUpload: "Start an artifact upload",
  takoformAbandonArtifactUpload: "Abandon an artifact upload",
  takoformCommitArtifactUpload: "Commit an artifact upload",
  takoformUploadArtifactBlob: "Upload one declared blob",
  takoformReadArtifactManifest: "Read a committed manifest",
  takoformHeadArtifactBlob: "Check whether a blob is held",
};

const IDENTIFIER_SCHEMA = { type: "string", minLength: 1, maxLength: 128 } as const;
const RESOURCE_NAME_SCHEMA = {
  type: "string",
  minLength: 1,
  maxLength: 128,
  pattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
} as const;
const SPACE_ID_SCHEMA = {
  type: "string",
  description:
    "Opaque stable Host Space identifier: 1-255 Unicode code points, with no slash, C0/C1 control, or boundary whitespace.",
  minLength: 1,
  maxLength: SPACE_ID_MAX_CODE_POINTS,
  pattern: SPACE_ID_PATTERN_SOURCE,
} as const;
const OPERATION_KEY_SCHEMA = {
  type: "string",
  minLength: 8,
  maxLength: 128,
  pattern: "^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$",
} as const;
const CANONICAL_HTTPS_ORIGIN_SCHEMA = {
  type: "string",
  format: "uri",
  pattern: "^https://[^/]+$",
  maxLength: 2_048,
} as const;
/**
 * The address a Worker endpoint is published at.
 *
 * `http` belongs here and not in the schema above: the scheme of a published
 * Worker address is a fact about the runtime socket that serves it, and a
 * certificate-less self-host serves plain HTTP
 * (ADR 0009). This Host's *own* canonical public origin, which the
 * runtime-input route fences against, remains HTTPS-only.
 */
const PUBLISHED_WORKER_ORIGIN_SCHEMA = {
  type: "string",
  format: "uri",
  pattern: "^https?://[^/]+$",
  maxLength: 2_048,
} as const;
const REQUESTED_SUBDOMAIN_SCHEMA = {
  type: "string",
  minLength: 1,
  maxLength: 63,
  pattern: "^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$",
} as const;

const RESERVATION_ID_PARAMETER = {
  name: "reservationId",
  in: "path",
  required: true,
  schema: IDENTIFIER_SCHEMA,
} as const;

const WORKER_ENDPOINT_ORIGIN_RESERVATION_OPERATIONS = {
  put: {
    summary: "Prepare or exactly replay a future Worker endpoint origin reservation",
    parameters: [RESERVATION_ID_PARAMETER],
    requestBody: {
      required: true,
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/WorkerEndpointOriginReservationRequest" },
        },
      },
    },
    responses: {
      "201": currentReservationResponse(
        "Prepared reservation; an exact replay returns the same closed projection",
      ),
      "400": errorResponse("Malformed or open request"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "409": errorResponse("Replay, requested-subdomain, canonical-origin, or placement conflict"),
      "422": errorResponse("No unique eligible ModuleWorker offering or provider capability"),
      "503": errorResponse("Placement or reservation authority unavailable"),
    },
  },
  get: {
    summary: "Read one live Worker endpoint origin reservation",
    parameters: [RESERVATION_ID_PARAMETER],
    responses: {
      "200": reservationResponse("Live value-free reservation projection"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "404": errorResponse("Reservation absent, released, or expired"),
    },
  },
  delete: {
    summary: "Release a Worker endpoint origin reservation",
    description:
      "Idempotent after release. Activation must first be deleted, and a retained endpoint UID " +
      "continues to fence release until that exact Resource is deleted with closed provider absence.",
    parameters: [RESERVATION_ID_PARAMETER],
    responses: {
      "204": { description: "Released or already absent/released" },
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "409": errorResponse("Still activated, claimed, or fenced by the retained endpoint"),
      "503": errorResponse("Reservation authority unavailable"),
    },
  },
} as const;

const WORKER_ENDPOINT_ORIGIN_ACTIVATION_OPERATIONS = {
  put: reservationActivationOperation(
    "Activate the reservation against one exact realized Ready WorkerEndpoint",
  ),
  delete: reservationActivationOperation(
    "Deactivate the exact endpoint while retaining its UID as the release witness",
  ),
} as const;

const RUNTIME_INPUT_PREPARATION_OPERATIONS = {
  put: {
    summary: "Prepare one encrypted Worker runtime-input handoff",
    parameters: runtimeInputPathParameters(),
    requestBody: {
      required: true,
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/WorkerRuntimeInputPreparationRequest" },
        },
      },
    },
    responses: {
      "200": runtimeInputResponse("Prepared value-free handoff projection"),
      "400": errorResponse("Malformed request, wrong Host origin, or wrong operation key"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "409": errorResponse("The operation key already carries a different or spent handoff"),
      "503": errorResponse("Sealing or authority unavailable"),
    },
  },
  get: {
    summary: "Read a Worker runtime-input handoff without secret values",
    parameters: runtimeInputPathParameters(),
    responses: {
      "200": runtimeInputResponse("Value-free lifecycle projection"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "404": errorResponse("No live handoff exists for this operation key"),
    },
  },
  delete: {
    summary: "Revoke one undispatched Worker runtime-input handoff",
    parameters: runtimeInputPathParameters(),
    responses: {
      "204": { description: "Revoked or already revoked" },
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "409": errorResponse("The handoff is already dispatched or indeterminate"),
    },
  },
} as const;

const ARTIFACT_CONSUMER_REPAIR_PARAMETERS = [
  {
    name: "organizationId",
    in: "path",
    required: true,
    schema: IDENTIFIER_SCHEMA,
  },
  {
    name: "deploymentId",
    in: "path",
    required: true,
    schema: IDENTIFIER_SCHEMA,
  },
] as const;

const ARTIFACT_CONSUMER_REPAIR_OPERATIONS = {
  get: {
    summary: "Read the provider-backed repair plan for one uncertain artifact consumer",
    description:
      "Lifecycle-owner surface. This canonicalizes the current database snapshot but performs no provider readback and no mutation.",
    parameters: ARTIFACT_CONSUMER_REPAIR_PARAMETERS,
    responses: {
      "200": artifactConsumerRepairStatusResponse(),
      "400": errorResponse("Malformed organization or deployment identity"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:read"),
      "404": errorResponse("Deployment or uncertainty not found"),
      "503": errorResponse("Lifecycle state unavailable or malformed"),
    },
  },
  post: {
    summary: "Apply one exact provider-backed artifact-consumer repair plan",
    description:
      "Recomputes the plan, obtains fresh provider evidence, rechecks the entire snapshot, and commits through lifecycle-owned CAS. The caller supplies neither an outcome nor evidence.",
    parameters: [
      ...ARTIFACT_CONSUMER_REPAIR_PARAMETERS,
      {
        name: "Idempotency-Key",
        in: "header",
        required: true,
        schema: OPERATION_KEY_SCHEMA,
      },
    ],
    requestBody: {
      required: true,
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/ArtifactConsumerRepairApply" },
        },
      },
    },
    responses: {
      "200": artifactConsumerResolutionReceiptResponse(),
      "400": errorResponse("Malformed body, plan digest, or idempotency key"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "404": errorResponse("Deployment or uncertainty not found"),
      "409": errorResponse("Plan drift, blocked evidence, or idempotency conflict"),
      "503": errorResponse("Provider or lifecycle authority unavailable"),
    },
  },
} as const;

const OPERATIONS: Record<string, Record<string, unknown>> = {
  console: described("Console", { security: [] }),
  openapiDocument: described("This document", { security: [] }),
  productDiscovery: described("Product discovery", { security: [] }),
  takoformDiscovery: described("Stable Takoform Host discovery", {
    security: [],
  }),
  identityProviders: described("Identity providers accepted for sign-in", {
    security: [],
  }),
  createSession: described("Exchange an external assertion for a session", {
    security: [],
  }),
  endSession: {
    summary: "Sign out and revoke the current session",
    responses: {
      "204": { description: "The session is revoked and its cookie cleared" },
      "401": errorResponse("A session credential is required"),
    },
  },
  readPrincipal: described("Read the signed-in principal and the organizations it owns"),
  listAiModels: described("List configured OpenAI-compatible models"),
  createAiChatCompletion: described("Create a prepaid OpenAI-compatible chat completion", {
    parameters: [
      {
        name: "Idempotency-Key",
        in: "header",
        required: true,
        schema: { type: "string", minLength: 1, maxLength: 128 },
        description: "Stable per paid inference; replays return the same settled result.",
      },
      {
        name: "X-Takoserver-AI-Pricing-Revision",
        in: "header",
        required: false,
        schema: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
        description:
          "Optional exact model pricing revision from /v1/ai/models; drift is rejected before inference.",
      },
    ],
  }),
  listHostForms: described("List every Form definition this Host will accept", {
    security: [],
  }),
  createOrganization: described("Create an Organization"),
  createApiKey: described("Create a scoped API key"),
  listApiKeys: described("List the organization's live API keys"),
  prepareWorkerEndpointOriginReservation: WORKER_ENDPOINT_ORIGIN_RESERVATION_OPERATIONS.put,
  readWorkerEndpointOriginReservation: WORKER_ENDPOINT_ORIGIN_RESERVATION_OPERATIONS.get,
  releaseWorkerEndpointOriginReservation: WORKER_ENDPOINT_ORIGIN_RESERVATION_OPERATIONS.delete,
  activateWorkerEndpointOrigin: WORKER_ENDPOINT_ORIGIN_ACTIVATION_OPERATIONS.put,
  deactivateWorkerEndpointOrigin: WORKER_ENDPOINT_ORIGIN_ACTIVATION_OPERATIONS.delete,
  prepareWorkerRuntimeInput: RUNTIME_INPUT_PREPARATION_OPERATIONS.put,
  readWorkerRuntimeInput: RUNTIME_INPUT_PREPARATION_OPERATIONS.get,
  revokeWorkerRuntimeInput: RUNTIME_INPUT_PREPARATION_OPERATIONS.delete,
  listOrganizationResources: described("List the organization's Takoform resources", {
    parameters: [
      {
        name: "space",
        in: "query",
        required: false,
        schema: SPACE_ID_SCHEMA,
      },
    ],
  }),
  readOrganizationResource: described("Read one exact organization Takoform resource"),
  readNativeResidual: {
    summary: "Prove provider-native absence after a Resource delete",
    parameters: [
      {
        name: "space",
        in: "query",
        required: true,
        schema: SPACE_ID_SCHEMA,
      },
      {
        name: "name",
        in: "query",
        required: true,
        schema: { type: "string", minLength: 1, maxLength: 128 },
      },
    ],
    responses: {
      "200": {
        description: "Closed tri-state native absence attestation",
        content: {
          "application/json": {
            schema: {
              type: "object",
              required: ["residual"],
              additionalProperties: false,
              properties: {
                residual: {
                  type: "object",
                  required: ["status", "source", "effectCount", "deploymentCount", "checkedAt"],
                  additionalProperties: false,
                  properties: {
                    status: { type: "string", enum: ["absent", "present", "indeterminate"] },
                    source: { type: "string", enum: ["intrinsic", "provider"] },
                    evidenceRef: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
                    effectCount: { type: "integer", minimum: 0 },
                    deploymentCount: { type: "integer", minimum: 0 },
                    checkedAt: { type: "string", format: "date-time" },
                    reason: {
                      type: "string",
                      enum: [
                        "closure_pending",
                        "effect_unresolved",
                        "deployment_active",
                        "deployment_unmarked",
                        "provider_unavailable",
                        "provider_readback_failed",
                        "provider_identity_missing",
                        "legacy_unattested",
                      ],
                    },
                  },
                },
              },
            },
          },
        },
      },
      "400": errorResponse("Invalid exact address query"),
      "401": errorResponse("Authentication required"),
      "404": errorResponse("Resource incarnation not found"),
      "503": errorResponse("Absence evidence is unavailable"),
    },
  },
  readArtifactConsumerRepair: ARTIFACT_CONSUMER_REPAIR_OPERATIONS.get,
  applyArtifactConsumerRepair: ARTIFACT_CONSUMER_REPAIR_OPERATIONS.post,
  listResourceMigrations: described("List explicit provider migrations for one logical Resource"),
  planResourceMigration: described("Plan a migration against an exact commercial reservation"),
  readResourceMigration: described("Read one Resource Migration"),
  executeResourceMigration: described("Provision, transfer, and verify a candidate Deployment"),
  cutoverResourceMigration: described(
    "Atomically activate the candidate and re-resolve Attachments",
  ),
  rollbackResourceMigration: described(
    "Restore the retained Deployment and Attachment resolutions",
  ),
  cancelResourceMigration: described(
    "Delete an uncut candidate and release its commercial reservation",
  ),
  listAttachments: described("List the organization's Resource Attachments"),
  createAttachment: described("Resolve and create a Resource Attachment"),
  readAttachment: described("Read one Resource Attachment"),
  deleteAttachment: described("Delete one Resource Attachment"),
  listOrganizationOperations: described("List the organization's recent Takoform operations"),
  revokeApiKey: described("Revoke an API key"),
  readWallet: described("Read the prepaid wallet"),
  beginWalletCheckout: described("Begin a card payment for this organization"),
  creditWalletFromSettlement: described("Credit the wallet from a verified settlement proof"),
  listOfferings: described("List purchasable offerings"),
  createResellerQuote: described("Price an offering for a tenant"),
  createResellerReservation: described("Reserve a quote, holding funds"),
  captureResellerReservation: described("Capture a reservation against reported usage"),
  releaseResellerReservation: described("Release a reservation and return its hold"),
  mintProvisionToken: described("Mint a single-use provisioning token for a reservation"),
  mintTakoformRunToken: described(
    "Mint a short-lived exact-Resource bearer for an ordinary Takoform provider run",
  ),
  readUsageStatement: described("Read the usage statement of a captured reservation"),
};

function reservationResponse(description: string) {
  return {
    description,
    content: {
      "application/json": {
        schema: { $ref: "#/components/schemas/WorkerEndpointOriginReservation" },
      },
    },
  } as const;
}

function currentReservationResponse(description: string) {
  return {
    description,
    content: {
      "application/json": {
        schema: { $ref: "#/components/schemas/WorkerEndpointOriginReservationV2" },
      },
    },
  } as const;
}

function reservationActivationOperation(summary: string) {
  return {
    summary,
    parameters: [RESERVATION_ID_PARAMETER],
    requestBody: {
      required: true,
      content: {
        "application/json": {
          schema: {
            $ref: "#/components/schemas/WorkerEndpointOriginReservationActivationRequest",
          },
        },
      },
    },
    responses: {
      "200": reservationResponse("Updated reservation projection"),
      "400": errorResponse("Malformed or open request"),
      "401": errorResponse("Organization API key required"),
      "403": errorResponse("The key lacks resources:write"),
      "404": errorResponse("Reservation not found"),
      "409": errorResponse("Endpoint identity, relation, readiness, origin, or placement conflict"),
      "503": errorResponse("Reservation or Resource authority unavailable"),
    },
  } as const;
}

function runtimeInputPathParameters() {
  return [
    {
      name: "operationKey",
      in: "path",
      required: true,
      schema: OPERATION_KEY_SCHEMA,
    },
    {
      name: "Idempotency-Key",
      in: "header",
      required: true,
      description: "Must equal the operation key in the path.",
      schema: OPERATION_KEY_SCHEMA,
    },
  ] as const;
}

/**
 * One documented failure.
 *
 * Every error on the control lane and the Takoform Host lane is the same
 * closed envelope, so the document pins its shape rather than leaving the
 * status with a description and no schema. The released provider decodes an
 * envelope only when `code`, `message`, `requestId` and `retryable` are all
 * present; an undocumented shape is how a lane came to answer two members and
 * make its own 404 unreadable.
 */
function errorResponse(description: string) {
  return {
    description,
    content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } },
  } as const;
}

function runtimeInputResponse(description: string) {
  return {
    description,
    content: {
      "application/json": {
        schema: { $ref: "#/components/schemas/WorkerRuntimeInputPreparation" },
      },
    },
  } as const;
}

function artifactConsumerRepairStatusResponse() {
  return {
    description: "Canonical current repair status and plan digest",
    content: {
      "application/json": {
        schema: {
          type: "object",
          required: ["repair"],
          additionalProperties: false,
          properties: {
            repair: { $ref: "#/components/schemas/ArtifactConsumerRepairStatus" },
          },
        },
      },
    },
  } as const;
}

function artifactConsumerResolutionReceiptResponse() {
  return {
    description: "Durable append-only resolution receipt",
    content: {
      "application/json": {
        schema: {
          type: "object",
          required: ["receipt"],
          additionalProperties: false,
          properties: {
            receipt: { $ref: "#/components/schemas/ArtifactConsumerResolutionReceipt" },
          },
        },
      },
    },
  } as const;
}

/** One published operation description, addressed by its operation name. */
function described(
  summary: string,
  extra: {
    readonly security?: readonly unknown[];
    readonly parameters?: readonly unknown[];
  } = {},
): Record<string, unknown> {
  return {
    summary,
    responses: { "200": { description: "Success" } },
    ...(extra.security ? { security: extra.security } : {}),
    ...(extra.parameters ? { parameters: extra.parameters } : {}),
  };
}

/**
 * The published `paths` object, projected from the route table.
 *
 * Both directions are refused here rather than reviewed: a documented route
 * with no description cannot build, and a description no documented route names
 * cannot build. Internal seams are declared in the table and deliberately left
 * out of the document.
 */
function documentedPaths(): Record<string, Record<string, unknown>> {
  const paths: Record<string, Record<string, unknown>> = {};
  const used = new Set<string>();
  for (const route of ROUTES) {
    if (route.internal) continue;
    const described = OPERATIONS[route.operation];
    if (described === undefined) {
      throw new Error(`route ${route.method.toUpperCase()} ${route.pattern} has no description`);
    }
    used.add(route.operation);
    const methods = paths[route.pattern] ?? {};
    paths[route.pattern] = methods;
    methods[route.method] = described;
  }
  for (const lane of TAKOFORM_LANES) {
    for (const route of TAKOFORM_ROUTES) {
      const summary = TAKOFORM_OPERATION_SUMMARIES[route.operation];
      if (summary === undefined) {
        throw new Error(`Takoform Host route ${route.operation} has no summary`);
      }
      const pattern = takoformRoutePattern(lane, route.pattern);
      const methods = paths[pattern] ?? {};
      paths[pattern] = methods;
      methods[route.method] = { summary, responses: { "200": { description: "Success" } } };
    }
  }
  const unusedControl = Object.keys(OPERATIONS).filter((name) => !used.has(name));
  if (unusedControl.length > 0) {
    throw new Error(`described operations no route declares: ${unusedControl.join(", ")}`);
  }
  const declaredTakoform = new Set(TAKOFORM_ROUTES.map((route) => route.operation));
  const unusedTakoform = Object.keys(TAKOFORM_OPERATION_SUMMARIES).filter(
    (name) => !declaredTakoform.has(name),
  );
  if (unusedTakoform.length > 0) {
    throw new Error(`Takoform summaries no route declares: ${unusedTakoform.join(", ")}`);
  }
  return paths;
}

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Takoserver API",
    version: "1.0.0",
    summary: "An independent prepaid platform for Takoform-declared resources.",
  },
  servers: [{ url: "https://api.takoserver.com" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description:
          "A session secret, an organization API key, or a resource-scoped token, " +
          "depending on the route.",
      },
    },
    schemas: {
      Error: {
        type: "object",
        description:
          "The wire error envelope of the stable Takoform Host lane and the /v1/* control lane. Every response documented against this schema carries exactly these members. The OpenAI-compatible /v1/ai/* lane answers that API's own error shape and is documented separately.",
        required: ["error"],
        additionalProperties: false,
        properties: {
          error: {
            type: "object",
            required: ["code", "message", "requestId", "retryable"],
            additionalProperties: false,
            properties: {
              code: { type: "string", minLength: 1, maxLength: 64 },
              message: { type: "string", minLength: 1, maxLength: 256 },
              requestId: { type: "string", minLength: 1, maxLength: 128 },
              retryable: { type: "boolean" },
              hostCode: {
                description:
                  "This Host's own finer name for the refusal, when the closed portable code taxonomy cannot carry the distinction. The released provider decodes it alongside the portable code and never acts on it, so it refines a classification rather than replacing one. `cross_resource_precondition` marks a refusal whose truth is held by another resource, which this Host re-attempts rather than replays under the caller's idempotency key.",
                type: "string",
                minLength: 1,
                maxLength: 64,
              },
              details: {
                description: "Lane-specific, value-free detail. Never derived from a secret.",
              },
            },
          },
        },
      },
      ArtifactConsumerRepairApply: {
        type: "object",
        required: ["kind", "planDigest"],
        additionalProperties: false,
        properties: {
          kind: { const: ARTIFACT_CONSUMER_REPAIR_APPLY_FORMAT },
          planDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
        },
      },
      ArtifactConsumerResolutionReceipt: {
        type: "object",
        required: [
          "kind",
          "receiptId",
          "deploymentId",
          "uncertaintyFence",
          "planDigest",
          "resolution",
          "createdAt",
        ],
        additionalProperties: false,
        properties: {
          kind: { const: ARTIFACT_CONSUMER_RESOLUTION_RECEIPT_FORMAT },
          receiptId: IDENTIFIER_SCHEMA,
          deploymentId: IDENTIFIER_SCHEMA,
          uncertaintyFence: { type: "integer", minimum: 1 },
          planDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
          resolution: {
            type: "string",
            enum: ["terminalized_absent", "attributed_manifest"],
          },
          manifestDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
          createdAt: { type: "string", format: "date-time" },
        },
      },
      ArtifactConsumerRepairStatus: {
        type: "object",
        required: [
          "kind",
          "deploymentId",
          "state",
          "planDigest",
          "uncertaintyFence",
          "candidateManifestCount",
        ],
        additionalProperties: false,
        properties: {
          kind: { const: ARTIFACT_CONSUMER_REPAIR_STATUS_FORMAT },
          deploymentId: IDENTIFIER_SCHEMA,
          state: { type: "string", enum: ["actionable", "blocked", "resolved"] },
          planDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
          uncertaintyFence: { type: "integer", minimum: 1 },
          candidateManifestCount: { type: "integer", minimum: 0 },
          path: {
            type: "string",
            enum: ["retained-closed", "retained-historical", "active-resource"],
          },
          action: {
            type: "string",
            enum: ["verify-native-absence", "verify-artifact-consumption"],
          },
          blocker: { type: "string", minLength: 1, maxLength: 128 },
          receipt: { $ref: "#/components/schemas/ArtifactConsumerResolutionReceipt" },
        },
      },
      WorkerEndpointOriginReservationLegacyTarget: {
        type: "object",
        required: ["space", "workerName", "endpointName"],
        additionalProperties: false,
        properties: {
          space: SPACE_ID_SCHEMA,
          workerName: RESOURCE_NAME_SCHEMA,
          endpointName: RESOURCE_NAME_SCHEMA,
        },
      },
      WorkerEndpointOriginReservationRequest: {
        type: "object",
        required: ["format", "requestedSubdomain", "expiresInSeconds"],
        additionalProperties: false,
        properties: {
          format: { const: "takoserver.worker-endpoint-origin-reservation.v2" },
          requestedSubdomain: REQUESTED_SUBDOMAIN_SCHEMA,
          offeringId: IDENTIFIER_SCHEMA,
          expiresInSeconds: { type: "integer", minimum: 60, maximum: 86_400 },
        },
      },
      WorkerEndpointOriginReservationBinding: {
        type: "object",
        required: ["space", "workerName", "workerResourceUid", "workerResourceRevision"],
        additionalProperties: false,
        oneOf: [
          {
            not: {
              anyOf: [
                { required: ["endpointName"] },
                { required: ["endpointResourceUid"] },
                { required: ["endpointResourceRevision"] },
              ],
            },
          },
          {
            required: ["endpointName", "endpointResourceUid", "endpointResourceRevision"],
          },
        ],
        properties: {
          space: SPACE_ID_SCHEMA,
          workerName: RESOURCE_NAME_SCHEMA,
          workerResourceUid: IDENTIFIER_SCHEMA,
          workerResourceRevision: { type: "string", pattern: "^[1-9][0-9]*$" },
          endpointName: RESOURCE_NAME_SCHEMA,
          endpointResourceUid: IDENTIFIER_SCHEMA,
          endpointResourceRevision: { type: "string", pattern: "^[1-9][0-9]*$" },
        },
      },
      WorkerEndpointOriginReservationV2: {
        type: "object",
        required: [
          "format",
          "reservationId",
          "requestedSubdomain",
          "canonicalPublicOrigin",
          "revision",
          "expiresAt",
          "status",
        ],
        additionalProperties: false,
        oneOf: [
          {
            properties: { status: { const: "prepared" } },
            not: { required: ["binding"] },
          },
          {
            properties: { status: { const: "bound" } },
            required: ["binding"],
          },
          {
            properties: {
              status: { const: "activated" },
              binding: {
                allOf: [
                  { $ref: "#/components/schemas/WorkerEndpointOriginReservationBinding" },
                  {
                    required: ["endpointName", "endpointResourceUid", "endpointResourceRevision"],
                  },
                ],
              },
            },
            required: ["binding"],
          },
        ],
        properties: {
          format: { const: "takoserver.worker-endpoint-origin-reservation.v2" },
          reservationId: IDENTIFIER_SCHEMA,
          requestedSubdomain: REQUESTED_SUBDOMAIN_SCHEMA,
          canonicalPublicOrigin: PUBLISHED_WORKER_ORIGIN_SCHEMA,
          revision: { type: "string", pattern: "^[1-9][0-9]*$" },
          expiresAt: { type: "string", format: "date-time" },
          status: { type: "string", enum: ["prepared", "bound", "activated"] },
          binding: { $ref: "#/components/schemas/WorkerEndpointOriginReservationBinding" },
        },
      },
      WorkerEndpointOriginReservationV1: {
        type: "object",
        required: [
          "format",
          "reservationId",
          "canonicalPublicOrigin",
          "revision",
          "expiresAt",
          "target",
          "status",
        ],
        additionalProperties: false,
        properties: {
          format: { const: "takoserver.worker-endpoint-origin-reservation.v1" },
          reservationId: IDENTIFIER_SCHEMA,
          canonicalPublicOrigin: PUBLISHED_WORKER_ORIGIN_SCHEMA,
          revision: { type: "string", pattern: "^[1-9][0-9]*$" },
          expiresAt: { type: "string", format: "date-time" },
          target: { $ref: "#/components/schemas/WorkerEndpointOriginReservationLegacyTarget" },
          status: { type: "string", enum: ["prepared", "bound", "activated"] },
          workerResourceUid: IDENTIFIER_SCHEMA,
          endpointResourceUid: IDENTIFIER_SCHEMA,
        },
      },
      WorkerEndpointOriginReservation: {
        oneOf: [
          { $ref: "#/components/schemas/WorkerEndpointOriginReservationV2" },
          { $ref: "#/components/schemas/WorkerEndpointOriginReservationV1" },
        ],
      },
      WorkerEndpointOriginReservationActivationRequest: {
        type: "object",
        required: ["format", "endpointResourceUid"],
        additionalProperties: false,
        properties: {
          format: { const: "takoserver.worker-endpoint-origin-reservation-activation.v2" },
          endpointResourceUid: IDENTIFIER_SCHEMA,
        },
      },
      WorkerRuntimeInputPublicApply: {
        type: "object",
        description:
          "The exact ordinary public apply this handoff authorizes. The host commits to it as the length-prefixed SHA-256 of [label, method, path, ifNoneMatch, body].",
        required: ["method", "path", "fences", "body"],
        additionalProperties: false,
        properties: {
          method: { const: "PUT" },
          path: { type: "string", minLength: 1, maxLength: 8_192, pattern: "^/" },
          fences: {
            type: "object",
            required: ["ifNoneMatch"],
            additionalProperties: false,
            properties: { ifNoneMatch: { const: "*" } },
          },
          body: { type: "string", minLength: 1, maxLength: 1_048_576 },
        },
      },
      WorkerRuntimeInputPreparationRequest: {
        type: "object",
        required: ["format", "canonicalPublicOrigin", "publicApply", "bindings"],
        additionalProperties: false,
        properties: {
          format: { const: "takoserver.worker-runtime-input-preparation@v2" },
          canonicalPublicOrigin: CANONICAL_HTTPS_ORIGIN_SCHEMA,
          publicApply: { $ref: "#/components/schemas/WorkerRuntimeInputPublicApply" },
          bindings: {
            type: "object",
            minProperties: 1,
            maxProperties: 64,
            propertyNames: { pattern: "^[A-Z_][A-Z0-9_]{0,127}$" },
            additionalProperties: { type: "string", minLength: 1, maxLength: 32_768 },
          },
        },
      },
      WorkerRuntimeInputPreparation: {
        type: "object",
        required: [
          "format",
          "status",
          "operationKey",
          "applyCommitment",
          "canonicalPublicOrigin",
          "bindingNames",
        ],
        additionalProperties: false,
        properties: {
          format: { const: "takoserver.worker-runtime-input-preparation@v2" },
          status: {
            type: "string",
            enum: ["prepared", "accepted", "dispatched", "consumed"],
          },
          operationKey: OPERATION_KEY_SCHEMA,
          applyCommitment: { type: "string", pattern: "^sha256:[0-9a-f]{64}$" },
          canonicalPublicOrigin: CANONICAL_HTTPS_ORIGIN_SCHEMA,
          bindingNames: {
            type: "array",
            minItems: 1,
            maxItems: 64,
            uniqueItems: true,
            items: { type: "string", pattern: "^[A-Z_][A-Z0-9_]{0,127}$" },
          },
          hostOperationId: {
            type: "string",
            description: "Present exactly when the handoff has been claimed by a Host operation.",
            pattern: "^op_[A-Za-z0-9][A-Za-z0-9._-]{0,124}$",
          },
        },
      },
    },
  },
  paths: documentedPaths(),
} as const;

/**
 * Build the served document for one deployment. The checked artifact keeps the
 * stable production origin above, while each running deployment advertises the
 * public origin selected by its environment (or by an explicit local/test
 * composition).
 */
export function createOpenApiDocument(publicOrigin: string) {
  return { ...openApiDocument, servers: [{ url: publicOrigin }] };
}

/** Every path the document declares, sorted. Used by the contract test. */
export function openApiPaths(): readonly string[] {
  return Object.keys(openApiDocument.paths).sort();
}
