/**
 * The published API description.
 *
 * The Takoform lane is mirrored across two versions that are wire-identical, so
 * those paths are generated from one list rather than written twice — a
 * hand-maintained mirror is a mirror that eventually stops matching. The
 * document is a checked build product: `openapi/takoserver.openapi.json` is
 * regenerated by `bun run openapi:write` and compared byte for byte in the
 * gate, so it can never drift from this source.
 */

const TAKOFORM_LANES = ["v1beta1", "v1alpha3"] as const;

/** Every Takoform Host path, relative to a lane mount. */
const TAKOFORM_PATHS: readonly {
  readonly path: string;
  readonly methods: readonly { readonly method: string; readonly summary: string }[];
}[] = [
  { path: "/forms", methods: [{ method: "get", summary: "Resolve one exact installed Form" }] },
  {
    path: "/form-definitions/{group}/{version}/{kind}",
    methods: [{ method: "get", summary: "Read an installed Form definition" }],
  },
  {
    path: "/support/forms",
    methods: [{ method: "get", summary: "List support profiles for installed Forms" }],
  },
  {
    path: "/support/forms/{group}/{version}/{kind}/{definitionVersion}",
    methods: [{ method: "get", summary: "Read one Form support profile" }],
  },
  {
    path: "/support/interfaces/{name}/{version}",
    methods: [{ method: "get", summary: "Read a provided Interface contract" }],
  },
  {
    path: "/support/bindings/{name}/{version}",
    methods: [{ method: "get", summary: "Read an accepted Binding contract" }],
  },
  {
    path: "/resources/validate",
    methods: [{ method: "post", summary: "Validate desired state without recording it" }],
  },
  {
    path: "/resources/prepare",
    methods: [{ method: "post", summary: "Review desired state and mint a prepare digest" }],
  },
  {
    path: "/resources/{group}/{version}/{kind}/{name}",
    methods: [
      { method: "get", summary: "Read a resource" },
      { method: "put", summary: "Apply reviewed desired state" },
      { method: "delete", summary: "Delete a resource" },
    ],
  },
  {
    path: "/resources/{group}/{version}/{kind}/{name}/observe",
    methods: [{ method: "post", summary: "Refresh observed state from the backend" }],
  },
  {
    path: "/resources/{group}/{version}/{kind}/{name}/import",
    methods: [{ method: "post", summary: "Adopt an existing native resource" }],
  },
  {
    path: "/operations/{operationId}",
    methods: [{ method: "get", summary: "Read a settled operation" }],
  },
  {
    path: "/operations/{operationId}/cancel",
    methods: [{ method: "post", summary: "Request cancellation of an operation" }],
  },
  {
    path: "/artifacts/uploads",
    methods: [{ method: "post", summary: "Start an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}",
    methods: [{ method: "delete", summary: "Abandon an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}/commit",
    methods: [{ method: "post", summary: "Commit an artifact upload" }],
  },
  {
    path: "/artifacts/uploads/{uploadId}/blobs/{digest}",
    methods: [{ method: "put", summary: "Upload one declared blob" }],
  },
  {
    path: "/artifacts/{digest}",
    methods: [{ method: "get", summary: "Read a committed manifest" }],
  },
  {
    path: "/artifacts/blobs/{digest}",
    methods: [{ method: "head", summary: "Check whether a blob is held" }],
  },
];

const PUBLIC_PATHS: Record<string, Record<string, unknown>> = {
  "/": operation("get", "Console", { security: [] }),
  "/openapi.json": operation("get", "This document", { security: [] }),
  "/.well-known/takoserver": operation("get", "Product discovery", { security: [] }),
  "/.well-known/takoform/v1beta1": operation("get", "Released Takoform lane discovery", {
    security: [],
  }),
  "/.well-known/takoform/v1alpha3": operation("get", "Current Takoform lane discovery", {
    security: [],
  }),
  "/v1/identity/providers": operation("get", "Identity providers accepted for sign-in", {
    security: [],
  }),
  "/v1/sessions": operation("post", "Exchange an external assertion for a session", {
    security: [],
  }),
  "/v1/me": operation("get", "Read the signed-in principal and the organizations it owns"),
  "/v1/forms": operation("get", "List every Form definition this Host will accept", {
    security: [],
  }),
  "/v1/organizations": operation("post", "Create an Organization"),
  "/v1/organizations/{organizationId}/api-keys": operations({
    post: "Create a scoped API key",
    get: "List the organization's live API keys",
  }),
  "/v1/organizations/{organizationId}/resources": operation(
    "get",
    "List the organization's Takoform resources",
  ),
  "/v1/organizations/{organizationId}/resources/{resourceUid}/data-tokens": operation(
    "post",
    "Mint a short-lived token for one resource's data plane",
  ),
  "/data/v1/objects/{resourceUid}": operation("get", "List what a bucket holds", {
    security: [{ dataToken: [] }],
  }),
  "/data/v1/objects/{resourceUid}/{key}": operations({
    put: "Write an object",
    get: "Read an object",
    head: "Read an object's metadata",
    delete: "Remove an object",
  }),
  "/v1/organizations/{organizationId}/operations": operation(
    "get",
    "List the organization's recent Takoform operations",
  ),
  "/v1/organizations/{organizationId}/api-keys/{apiKeyId}": operation(
    "delete",
    "Revoke an API key",
  ),
  "/v1/organizations/{organizationId}/wallet": operation("get", "Read the prepaid wallet"),
  "/v1/organizations/{organizationId}/wallet/checkout": operation(
    "post",
    "Begin a card payment for this organization",
  ),
  "/v1/organizations/{organizationId}/wallet/funding": operation(
    "post",
    "Credit the wallet from a verified settlement proof",
  ),
  "/v1/catalog": operation("get", "List purchasable offerings"),
  "/v1/reseller/quotes": operation("post", "Price an offering for a tenant"),
  "/v1/reseller/reservations": operation("post", "Reserve a quote, holding funds"),
  "/v1/reseller/reservations/{reservationId}/capture": operation(
    "post",
    "Capture a reservation against reported usage",
  ),
  "/v1/reseller/reservations/{reservationId}/release": operation(
    "post",
    "Release a reservation and return its hold",
  ),
  "/v1/reseller/reservations/{reservationId}/provision-tokens": operation(
    "post",
    "Mint a single-use provisioning token for a reservation",
  ),
  "/v1/reseller/reservations/{reservationId}/usage-statement": operation(
    "get",
    "Read the usage statement of a captured reservation",
  ),
};

/** One path that answers to more than one method. */
function operations(summaries: Readonly<Record<string, string>>): Record<string, unknown> {
  return Object.assign(
    {},
    ...Object.entries(summaries).map(([method, summary]) => operation(method, summary)),
  ) as Record<string, unknown>;
}

function operation(
  method: string,
  summary: string,
  extra: { readonly security?: readonly unknown[] } = {},
): Record<string, unknown> {
  return {
    [method]: {
      summary,
      responses: { "200": { description: "Success" } },
      ...(extra.security ? { security: extra.security } : {}),
    },
  };
}

function takoformPaths(): Record<string, Record<string, unknown>> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const lane of TAKOFORM_LANES) {
    for (const entry of TAKOFORM_PATHS) {
      const methods: Record<string, unknown> = {};
      for (const { method, summary } of entry.methods) {
        methods[method] = { summary, responses: { "200": { description: "Success" } } };
      }
      paths[`/apis/forms.takoform.com/${lane}${entry.path}`] = methods;
    }
  }
  return paths;
}

export const openApiDocument = {
  openapi: "3.1.0",
  info: {
    title: "Takoserver API",
    version: "0.2.0",
    summary: "An independent prepaid platform for Takoform-declared resources.",
  },
  servers: [{ url: "https://api.takoserver.com" }],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description:
          "A session secret, an organization API key, or a resource-scoped token, " +
          "depending on the route.",
      },
    },
  },
  paths: { ...PUBLIC_PATHS, ...takoformPaths() },
} as const;

/** Every path the document declares, sorted. Used by the contract test. */
export function openApiPaths(): readonly string[] {
  return Object.keys(openApiDocument.paths).sort();
}
