import type {
  InstalledTakoformBinding,
  InstalledTakoformForm,
  TakoformBindingRef,
} from "./types.ts";

export interface TakoformCatalogInput {
  readonly forms: readonly InstalledTakoformForm[];
  readonly bindings: readonly InstalledTakoformBinding[];
}

/**
 * Selects only definitions that explicitly require the literal stable Host.
 *
 * Released v1beta1 provider bytes remain useful only for historical recovery.
 * Current authoring is the exact versionless family generated by the owning
 * Forms repository; no retained identity is relabelled into this lane.
 */
export function currentTakoformCatalog(input: TakoformCatalogInput): TakoformCatalogInput {
  const forms = input.forms.filter((form) => form.requiresHostApi === "forms.takoform.com/v1");
  const accepted = new Set(forms.flatMap((form) => form.acceptedBindings ?? []).map(bindingRefKey));
  const bindings = input.bindings.filter((binding) =>
    accepted.has(bindingRefKey(binding.bindingRef)),
  );
  if (
    new Set(bindings.map((binding) => bindingRefKey(binding.bindingRef))).size !== accepted.size
  ) {
    throw new TypeError("current_takoform_binding_missing");
  }
  return { forms, bindings };
}

function bindingRefKey(ref: TakoformBindingRef): string {
  return `${ref.apiVersion}\0${ref.name}\0${ref.version}\0${ref.schemaDigest}`;
}
